// English translation. The key is the French text used in the code (see langue.js).
export const EN = {
// v9 : accueil raconté, boutique, ciel qui se construit, journal seul
"Bienvenue dans ton univers.": "Welcome to your universe.",
"Pour l’instant, il est vide. C’est à toi de le construire, une pensée à la fois.": "For now, it’s empty. It’s yours to build, one thought at a time.",
"Commencer": "Begin",
"Voici ta lueur.": "This is your glow.",
"Elle t’accompagne et grandit avec toi. Comment veux-tu l’appeler ?": "It keeps you company and grows with you. What will you call it?",
"Un prénom": "A name",
"Continuer": "Continue",
"Je choisirai plus tard": "I’ll choose later",
"Touche + pour écrire ta journée. Tu peux y glisser une photo.": "Tap + to write your day. You can add a photo too.",
"Ta première étoile.": "Your first star.",
"Chaque jour où tu écris en allume une nouvelle. Sa couleur, c’est ton humeur.": "Each day you write lights a new one. Its colour is your mood.",
"Ta poussière d’étoiles.": "Your stardust.",
"Tu en gagnes chaque jour où tu écris. Elle sert à personnaliser ta lueur et ton ciel, dans la boutique.": "You earn some every day you write. Use it in the shop to customise your glow and your sky.",
"Ouvrir la boutique": "Open the shop",
"Ton univers commence ici.": "Your universe starts here.",
"Reviens demain pour une nouvelle étoile. La boutique, tes réglages et la langue sont dans ⋯.": "Come back tomorrow for a new star. The shop, your settings and the language are in ⋯.",
"C’est parti": "Let’s go",
"+ ✦{n} poussière d’étoiles": "+ ✦{n} stardust",
"Passer": "Skip",
"Allumé": "On",
"Éteint": "Off",
"Tu gagnes ✦10 chaque jour où tu écris. Un objet acheté se rallume ou s’éteint d’un toucher.": "You earn ✦10 every day you write. Tap an item you own to turn it on or off.",
"De nouveaux objets arrivent au fil des jours.": "New items arrive as the days go by.",
"Prochain : {nom}, dans {d}.": "Next: {nom}, in {d}.",
"Tu as écrit {n} jour.": "You have written on {n} day.",
"Tu as écrit {n} jours.": "You have written on {n} days.",
"Ta première étoile": "Your first star",
"Le jour où tu écris pour la première fois.": "The day you write for the first time.",
"Tes constellations": "Your constellations",
"Les jours écrits à la suite se relient par un fil de lumière.": "Days written in a row are joined by a thread of light.",
"La poussière d’étoiles": "Stardust",
"Un voile fin apparaît autour de tes étoiles.": "A fine veil appears around your stars.",
"Les nébuleuses": "The nebulae",
"Les mois et les semaines deviennent des nuages de lumière.": "Months and weeks become clouds of light.",
"Les étoiles filantes": "Shooting stars",
"Elles traversent ton ciel de temps en temps, avec d’autres surprises.": "They cross your sky now and then, along with other surprises.",
"La Voie lactée": "The Milky Way",
"Une grande bande de lumière se dessine au loin.": "A great band of light appears in the distance.",
"Les aurores": "The auroras",
"Un rideau de lumière ondule parfois dans le ciel.": "A curtain of light sometimes ripples across the sky.",
"Ta première galaxie": "Your first galaxy",
"Une année entière d’écriture. La suite arrive à ce moment-là.": "A whole year of writing. What comes next arrives then.",
"Yeux étoilés": "Starry eyes",
"Un reflet en étoile dans les yeux de ta lueur.": "A star-shaped sparkle in your glow’s eyes.",
"Croix de lumière": "Light crosses",
"Tes étoiles brillent avec de longues branches.": "Your stars shine with long rays.",
"Filantes dorées": "Golden shooting stars",
"Des étoiles filantes dorées, plus souvent.": "Golden shooting stars, more often.",
"Journée vide. Raconte-la.": "An empty day. Tell its story.",
"+ Écrire": "+ Write",
"Nouveau dans ton ciel : {nom}": "New in your sky: {nom}",
"nouvelle pensee journal intime photo video": "new thought journal diary photo video",
"Boutique": "Shop",
"poussiere etoiles acheter objets": "stardust buy items shop",
"Mon ciel": "My sky",
"paliers ciel grandir debloquer": "milestones sky grow unlock",
"Boutique, ton ciel, personnaliser ta lueur": "Shop, your sky, customise your glow",
"Des objets pour ta lueur et ton ciel": "Items for your glow and your sky",
"Ce qui pousse quand tu écris": "What grows when you write",
"+ Photo ou vidéo": "+ Photo or video",
"Le mois": "The month",
"Photo ou vidéo": "Photo or video",
"Menu": "Menu",
"‹ Menu": "‹ Menu",
"Chercher une commande ou une pensée": "Search a command or a thought",
"Ta petite lueur : la personnaliser, un souvenir": "Your little glow: customise it, a memory",
"Personnaliser": "Customise",
"Couleur, yeux, accessoire, taille": "Colour, eyes, accessory, size",
"Elle va relire une ancienne pensée": "It will reread an old thought",
"Renommer": "Rename",
"La boutique, les quêtes du jour et le chemin arriveront ici.": "The shop, daily quests and the path will arrive here.",
"Suivi": "Tracking",
"Tes humeurs sur 30 jours et le résumé du mois": "Your moods over 30 days and the month summary",
"Filtres": "Filters",
"Filtre actif : #{tag}": "Active filter: #{tag}",
"Ne montrer que les jours d’un #mot": "Only show the days of a #word",
"Écris un #mot dans une entrée (par exemple #famille) : il deviendra un filtre.": "Write a #word in an entry (for example #family): it will become a filter.",
"Rappel du soir, langue, sauvegarde, aide": "Evening reminder, language, backup, help",
"Mes données": "My data",
"Aide": "Help",
"Calme": "Calm",
"Joie": "Joy",
"Élan": "Drive",
"Mélancolie": "Melancholy",
"Tempête": "Storm",
"calme": "calm",
"joie": "joy",
"élan": "drive",
"mélancolie": "melancholy",
"tempête": "storm",
"Journal": "Journal",
"Note": "Note",
"Notes": "Notes",
"Tâche": "Task",
"Tâches": "Tasks",
"Média": "Media",
"Médias": "Media",
"Nuit": "Night",
"Aube": "Dawn",
"Océan": "Ocean",
"Papier": "Paper",
"hiver": "winter",
"printemps": "spring",
"été": "summer",
"automne": "autumn",
"Votre journal : une étoile par jour": "Your journal: one star per day",
"Position dans le temps": "Position in time",
"Retirer le filtre": "Remove the filter",
"Journée": "Day",
"Jour précédent": "Previous day",
"Jour suivant": "Next day",
"Date qui compte": "Date that matters",
"Marquer une date qui compte": "Mark a date that matters",
"Fermer la journée": "Close the day",
"Nouvelle entrée": "New entry",
"Type d’entrée": "Entry type",
"Fermer (le brouillon est gardé)": "Close (the draft is kept)",
"Mise en forme": "Formatting",
"Titre 1": "Heading 1",
"Titre 2": "Heading 2",
"Titre 3": "Heading 3",
"+ Ajouter": "+ Add",
"Ajouter un bloc": "Add a block",
"ou tapez / en début de ligne": "or type / at the start of a line",
"Liste à puces": "Bulleted list",
"Liste numérotée": "Numbered list",
"Texte simple": "Plain text",
"Titre 4": "Heading 4",
"Citation": "Quote",
"Séparateur": "Divider",
"Image": "Image",
"Vidéo": "Video",
"Texte": "Text",
"Fermer le clavier": "Close keyboard",
"Fichier trop lourd (150 Mo maximum)": "File too large (150 MB maximum)",
"Fermer": "Close",
"Qu’est-ce qui traverse ?": "What’s on your mind?",
"Jour": "Day",
"Jour de l’entrée": "Day of the entry",
"Humeur du jour": "Mood of the day",
"Titre (facultatif)": "Title (optional)",
"Titre de la note": "Note title",
"Écrivez. Ce texte ne quitte jamais cet appareil.": "Write. This text never leaves this device.",
"Prendre une photo": "Take a photo",
"Choisir dans la galerie": "Choose from gallery",
"Dicter à la voix": "Dictate by voice",
"Dicter": "Dictate",
"Annuler": "Cancel",
"Enregistrer": "Save",
"Une date qui compte": "A date that matters",
"Anniversaire de…, départ, rendez-vous…": "…’s birthday, a departure, an appointment…",
"Titre": "Title",
"Chaque année": "Every year",
"Retirer": "Remove",
"Marquer": "Mark",
"Personnaliser la lueur": "Customise the glow",
"Ma lueur": "My glow",
"Nommer la petite lueur": "Name the little glow",
"Une petite lueur vous a trouvé.": "A little glow has found you.",
"Comment voulez-vous l’appeler ?": "What would you like to call it?",
"Lueur": "Glow",
"Nom de la lueur": "Name of the glow",
"Adopter": "Adopt",
"Comment voyager dans le ciel": "How to travel through the sky",
"Voyager dans le temps": "Travel through time",
"Effacer les exemples": "Clear the examples",
"Compris": "Got it",
"Analyses": "Insights",
"Réglages": "Settings",
"Arrêter": "Stop",
"Écrire": "Write",
"Écrire (N)": "Write (N)",
"Commandes": "Commands",
"Commandes ( / )": "Commands ( / )",
"commandes": "commands",
"Aller à aujourd’hui": "Go to today",
"aujourd’hui": "today",
"Aujourd’hui": "Today",
"Zoom dans le temps": "Zoom through time",
"Plonger d’un niveau": "Dive one level",
"Plonger (zoom avant)": "Dive (zoom in)",
"Remonter d’un niveau": "Go up one level",
"Remonter (zoom arrière)": "Go up (zoom out)",
"une commande, ou une idée à retrouver…": "a command, or an idea to find…",
"Commande ou recherche": "Command or search",
"choisir ·": "choose ·",
"valider ·": "confirm ·",
"fermer": "close",
"échap": "esc",
"Sens profond : non": "Deep meaning: no",
"Noms": "Names",
"Sauvegarde : non": "Backup: no",
"Exporter": "Export",
"Importer": "Import",
"Installer l’appli": "Install the app",
"Effacer les entrées d’exemple": "Clear the example entries",
"Entrée inventée pour l’exemple": "Made-up entry, just an example",
"exemple": "example",
"exemples": "examples",
"Voir toutes les entrées #{tag}": "See all entries #{tag}",
"Modifier": "Edit",
"modifier": "edit",
"Supprimer": "Delete",
"supprimer": "delete",
"Modifier la tâche": "Edit the task",
"Supprimer la tâche": "Delete the task",
"Ouvrir {nom}": "Open {nom}",
"le média": "the media",
"introuvable": "not found",
"Modifier cette date": "Edit this date",
"{n} an": "{n} year",
"{n} ans": "{n} years",
"Couleur libre": "Free colour",
"couleur libre": "free colour",
"humeur ?": "mood?",
"Journée vide. Ajoutez une première entrée.": "Empty day. Add a first entry.",
"éclaircie": "clear",
"orage": "storm",
"{n} j": "{n} d",
"Météo intérieure": "Inner weather",
"Bilan du mois": "Month in review",
"{n} jours": "{n} days",
"{n} jour": "{n} day",
"Courbe de l’humeur dans le temps": "Mood curve over time",
"Mois précédent": "Previous month",
"Mois suivant": "Next month",
"Bilan": "Review",
"Survoler le mois": "Fly over the month",
"Aucune pensée sur cette période : le ciel est vide.": "No thoughts in this period: the sky is empty.",
"plutôt dégagé": "mostly clear",
"variable": "changeable",
"nuageux": "cloudy",
"orageux": "stormy",
"Ciel {ciel}. {a}, {b}, {c} sur {n}.": "Sky {ciel}. {a}, {b}, {c} out of {n}.",
"{n} éclaircie": "{n} clear spell",
"{n} éclaircies": "{n} clear spells",
"{n} orage": "{n} storm",
"{n} orages": "{n} storms",
"{n} jour écrit": "{n} day written",
"{n} jours écrits": "{n} days written",
"lumineux": "bright",
"porté par l’élan": "carried by drive",
"voilé de mélancolie": "veiled in melancholy",
"agité": "restless",
"Aucune pensée ce mois-ci.": "No thoughts this month.",
"{a} sur {b}.": "{a} over {b}.",
"{n} pensée": "{n} thought",
"{n} pensées": "{n} thoughts",
"Le ciel a été surtout {adj} ({liste}).": "The sky was mostly {adj} ({liste}).",
"La seconde moitié du mois s’éclaircit.": "The second half of the month brightens.",
"La seconde moitié du mois s’assombrit.": "The second half of the month darkens.",
"Le mois est resté d’une humeur stable.": "The month stayed in a steady mood.",
"Reviennent souvent : {mots}.": "Often recurring: {mots}.",
"Le jour le plus lumineux : {d}.": "The brightest day: {d}.",
"{quand} : rien d’écrit pour l’instant.": "{quand}: nothing written yet.",
"{quand} : {n} sur {total}": "{quand}: {n} out of {total}",
"plutôt lumineuse": "rather bright",
"plus lourde que d’habitude": "heavier than usual",
"en équilibre": "balanced",
", surtout {humeur} ({ton}).": ", mostly {humeur} ({ton}).",
"semaine du {d}": "week of {d}",
"Semaine du {d}": "Week of {d}",
"Cette semaine": "This week",
"Ce mois-ci": "This month",
"En {mois}": "In {mois}",
"Série actuelle : {a} · record : {r}": "Current streak: {a} · record: {r}",
"Années": "Years",
"série de {n} jours": "{n}-day streak",
"Matière": "Texture",
"Brume": "Haze",
"Scintillement": "Twinkle",
"Animation du ciel": "Sky animation",
"Rotation": "Rotation",
"Optique": "Optics",
"Profondeur de champ": "Depth of field",
"Cinéma": "Cinema",
"Ciel {nom}": "{nom} sky",
"Ciel": "Sky",
"Humeurs": "Moods",
"rétablir": "reset",
"nommer cette ambiance": "name this look",
"Nom du look": "Look name",
"Looks": "Looks",
"Activé": "On",
"Désactivé": "Off",
"Heure du rappel": "Reminder time",
"Ce navigateur ne gère pas les notifications : le rappel apparaît dans l’appli quand elle est ouverte.": "This browser doesn’t support notifications: the reminder shows up in the app while it’s open.",
"Notifications autorisées. Le rappel s’affiche si rien n’est écrit ce jour-là.": "Notifications allowed. The reminder appears if nothing has been written that day.",
"Notifications bloquées dans le navigateur : le rappel n’apparaît que dans l’appli ouverte.": "Notifications blocked in the browser: the reminder only appears in the open app.",
"Au premier activage, le navigateur vous demande l’autorisation.": "The first time you turn it on, the browser asks for permission.",
"Rappel du soir": "Evening reminder",
"Rappel quotidien": "Daily reminder",
"Heure": "Time",
"envoyer un test": "send a test",
"Appli fermée : il faut l’avoir installée (Chrome, Edge, Android) ; sur iPhone, ajoutez-la d’abord à l’écran d’accueil.": "App closed: it must be installed (Chrome, Edge, Android); on iPhone, add it to the Home Screen first.",
"Aucun": "None",
"Anneau": "Ring",
"Antenne": "Antenna",
"Lunettes": "Glasses",
"Couronne": "Crown",
"Chapeau": "Hat",
"Petits": "Small",
"Normaux": "Normal",
"Grands": "Large",
"Suit mon humeur": "Follows my mood",
"Couleur : suit mon humeur": "Colour: follows my mood",
"Couleur": "Colour",
"Couleurs": "Colours",
"Accessoire": "Accessory",
"Couleur de l’accessoire": "Accessory colour",
"Yeux": "Eyes",
"Taille": "Size",
"Magie": "Magic",
"Étincelles": "Sparkles",
"Changer de nom": "Change name",
"Chercher « {q} » dans mes pensées": "Search “{q}” in my thoughts",
"Écrire dans le journal": "Write in the journal",
"nouvelle pensee journal intime": "new thought journal diary write",
"Nouvelle note": "New note",
"note idee travail": "note idea work",
"Nouvelles tâches": "New tasks",
"tache todo liste faire travail": "task todo list work",
"Ajouter une photo ou une vidéo": "Add a photo or a video",
"media image photo video": "media image photo video",
"maintenant jour present etoile": "now day present star today",
"Personnaliser ma petite lueur": "Customize my little glow",
"creature mascotte couleur accessoire chapeau lunettes yeux taille": "creature mascot glow colour accessory hat glasses eyes size",
"anniversaire evenement important date etoile doree": "birthday anniversary event important date golden star",
"Prochaine date qui compte": "Next date that matters",
"anniversaire evenement a venir": "birthday anniversary event upcoming",
"Aucune date marquée. Ouvrez un jour, puis ☆.": "No date marked yet. Open a day, then ☆.",
"etiquette tag filtre": "label tag filter",
"Retirer le filtre #{tag}": "Remove the filter #{tag}",
"etiquette filtre effacer": "label tag filter clear",
"Vue d’ensemble : toutes les années": "Overview: all years",
"dezoomer annees general": "zoom out years overview",
"dezoomer parent": "zoom out up parent",
"notification rappel rituel heure": "notification reminder ritual time evening",
"humeur courbe analyses ciel": "mood curve insights sky weather",
"analyses resume survol mois": "insights summary review month",
"apparence lumiere couleurs looks optique": "settings appearance light colours looks optics",
"Masquer les noms des mois et des années": "Hide the names of months and years",
"Afficher les noms des mois et des années": "Show the names of months and years",
"noms etiquettes": "names labels",
"Ciel : {nom}": "Sky: {nom}",
"theme ambiance": "theme mood sky",
"actuel": "current",
"Sens profond": "Deep meaning",
"modele langage ia comprendre": "model language ai understand meaning",
"oui": "yes",
"non": "no",
"Sauvegarde automatique": "Automatic backup",
"dossier copie backup": "folder copy backup save",
"Sauvegarde": "Backup",
"reconnecter": "reconnect",
"Exporter le journal": "Export the journal",
"telecharger json": "download json export",
"Importer un journal": "Import a journal",
"fichier json": "file json import",
"exemples demo fictives": "examples demo sample fake clear",
"Installer l’application": "Install the app",
"Raconte-moi un souvenir": "Tell me a memory",
"souvenir ancienne pensee rappel creature lueur": "memory old thought remember creature glow",
"Pas encore de souvenir à portée de ciel.": "No memory within reach of the sky yet.",
"Appeler {nom}": "Call {nom}",
"la petite lueur": "the little glow",
"creature lueur venir": "creature glow come call",
"Renommer la petite lueur": "Rename the little glow",
"creature nom lueur": "creature name glow rename",
"Laisser la petite lueur dormir (la masquer)": "Let the little glow sleep (hide it)",
"Réveiller la petite lueur": "Wake the little glow",
"creature masquer afficher": "creature hide show glow",
"Elle est de retour.": "It’s back.",
"Aide : comment voyager dans le ciel": "Help: how to travel through the sky",
"aide tutoriel zoom comment": "help tutorial zoom how",
"Surprends-moi": "Surprise me",
"surprise hasard comete aurore baleine easter egg": "surprise random comet aurora whale easter egg",
"Plein écran": "Full screen",
"Quitter le plein écran": "Exit full screen",
"immersif": "immersive fullscreen",
"{n} entrée": "{n} entry",
"{n} entrées": "{n} entries",
"Aucune entrée avec #{tag}": "No entries with #{tag}",
"Aujourd’hui : {titre} !": "Today: {titre}!",
"{n} jours d’affilée. Continue !": "{n} days in a row. Keep going!",
"C’est ton record de série !": "That’s your best streak!",
"Et si on racontait aujourd’hui ?": "How about telling today’s story?",
"Dans {n} : {titre}.": "In {n}: {titre}.",
"Il fait froid dehors, pas ici.": "It’s cold outside, not in here.",
"Ça sent le printemps.": "Spring is in the air.",
"Les nuits d’été sont les plus douces.": "Summer nights are the sweetest.",
"J’aime l’automne et ses couleurs.": "I love autumn and its colours.",
"Supprimer ce média ?": "Delete this media?",
"Supprimer cette entrée ?": "Delete this entry?",
"une petite lueur": "a little glow",
"journée vide, cliquez pour écrire": "empty day, click to write",
"rien d’écrit": "nothing written",
"Choisir n’importe quelle couleur": "Pick any colour",
"Libre": "Free",
"Une note, une idée, une information": "A note, an idea, some information",
"Ce qu’il y a à faire": "Things to do",
"Des photos ou des vidéos pour cette journée": "Photos or videos for this day",
"Le contenu de la note… (#etiquette pour la retrouver)": "The note itself… (#label to find it again)",
"Une tâche par ligne": "One task per line",
"Une légende (facultatif)": "A caption (optional)",
"Brouillon retrouvé.": "Draft recovered.",
"Cristalliser": "Crystallize",
"Ajouter": "Add",
"Écrivez au moins quelques mots.": "Write at least a few words.",
"Une tâche par ligne.": "One task per line.",
"Une note vide ne dit rien.": "An empty note says nothing.",
"Choisissez au moins une photo ou une vidéo.": "Choose at least one photo or video.",
"Enregistrement des médias…": "Saving media…",
"Fichier": "File",
"La dictée utilise la reconnaissance vocale de votre navigateur : avec Chrome ou Edge, le son est envoyé à leurs serveurs pour être transcrit. Ce que vous écrivez au clavier, lui, reste sur votre appareil.": "Dictation uses your browser’s speech recognition: with Chrome or Edge, the audio is sent to their servers to be transcribed. What you type on the keyboard stays on your device.",
"Activer la dictée ?": "Turn on dictation?",
"Micro refusé : autorisez-le dans le navigateur.": "Microphone blocked: allow it in the browser.",
"Dictée indisponible ({e}).": "Dictation unavailable ({e}).",
"Arrêter la dictée": "Stop dictation",
"Télécharger un petit modèle de langage (≈120 Mo) pour mieux comprendre le sens ? Il s’exécute sur votre appareil, vos textes ne sont pas envoyés.": "Download a small language model (≈120 MB) to better understand meaning? It runs on your device; your texts are not sent anywhere.",
"Recalcul…": "Recalculating…",
"Modèle indisponible : on reste en mode léger.": "Model unavailable: staying in light mode.",
"Effacer les entrées d’exemple ?": "Clear the example entries?",
"Exemples effacés. Le ciel est à vous.": "Examples cleared. The sky is yours.",
"{n} vidéo ou fichier non inclus dans l’export (trop lourd).": "{n} video or file not included in the export (too large).",
"{n} vidéos ou fichiers non inclus dans l’export (trop lourds).": "{n} videos or files not included in the export (too large).",
"Fichier non reconnu.": "File not recognised.",
"Pour tester, activez d’abord le rappel et autorisez les notifications.": "To test, first turn on the reminder and allow notifications.",
"Sauvegarde reprise.": "Backup resumed.",
"Arrêter la sauvegarde automatique ? Les fichiers déjà écrits restent dans le dossier.": "Stop automatic backup? Files already written stay in the folder.",
"Sauvegarde dans « {nom} » (les photos et vidéos n’y sont pas copiées).": "Backing up to “{nom}” (photos and videos are not copied there).",
"Sauvegarde impossible : {e}": "Backup failed: {e}",
"Sauvegarde interrompue : reconnectez le dossier.": "Backup interrupted: reconnect the folder.",
"Constellation est installée.": "Constellation is installed.",
"{nom} vous attend : une pensée pour ce soir ?": "{nom} is waiting: a thought for tonight?",
"Votre lueur": "Your glow",
"Le jour s’éteint… une pensée pour ce soir ?": "The day is fading… a thought for tonight?",
"Une pensée pour ce soir ?": "A thought for tonight?",
"Bienvenue, {nom}.": "Welcome, {nom}.",
"Ce navigateur ne gère pas les notifications. Le rappel ne s’affichera que dans l’appli ouverte.": "This browser doesn’t support notifications. The reminder will only show in the open app.",
"Notifications refusées par le navigateur : le rappel ne s’affichera que dans l’appli ouverte.": "Notifications refused by the browser: the reminder will only show in the open app.",
"Rappel activé à {h}.": "Reminder set for {h}.",
"Rappel désactivé.": "Reminder turned off.",
"Stockage indisponible": "Storage unavailable",
"Type de fichier non pris en charge": "File type not supported",
"Vidéo trop lourde (150 Mo maximum)": "Video too large (150 MB maximum)",
"Chargement du modèle…": "Loading the model…",
"Modèle {p} %": "Model {p}%",
"{nom} a grandi.": "{nom} has grown.",
"J’ai grandi !": "I’ve grown!",
"Bonjour ! Moi, c’est {nom}.": "Hello! I’m {nom}.",
"hier": "yesterday",
"il y a {n} jours": "{n} days ago",
"Ça me fait plaisir !": "That makes me happy!",
"Oh, c’est beau.": "Oh, that’s beautiful.",
"Ça me touche.": "That touches me.",
"Je suis là.": "I’m here.",
"Courage…": "Hang in there…",
"Respire doucement.": "Breathe gently.",
"Oh… regarde là-haut.": "Oh… look up there.",
"Oh !": "Oh!",
"Miaou ?": "Meow?",
"Hm ? Oh, tu es là.": "Hm? Oh, you’re here.",
"Je t’écoute.": "I’m listening.",
"Alors, cette journée ?": "So, how was today?",
"Raconte-moi.": "Tell me.",
"Lalala~": "Lalala~",
"Tu danses avec moi ?": "Dance with me?",
"Tu m’avais manqué.": "I missed you.",
"Les étoiles brillent plus fort la nuit.": "The stars shine brighter at night.",
"Chut… écoute le ciel.": "Shh… listen to the sky.",
"Je me demande ce que tu vas écrire.": "I wonder what you’ll write.",
"Tu vois cette étoile ? C’est une journée.": "See that star? It’s a day.",
"Un petit tour ?": "A little tour?",
"Je suis bien, ici.": "I like it here.",
"Wouiii !": "Wheee!",
"On plonge ?": "Shall we dive?",
"Ça tourne !": "It’s spinning!",
"Haaaa !": "Whoaaa!",
"Vite, un vœu !": "Quick, make a wish!",
"Hihi.": "Hehe.",
"Encore !": "Again!",
"Mmh…": "Mmm…",
"Oh, ça chatouille !": "Oh, that tickles!",
"Merci.": "Thank you.",
"Me voilà !": "Here I am!",
"Aaah !": "Aaah!",
"Waouh !": "Wow!",
"Une baleine ?!": "A whale?!",
"La lune…": "The moon…",
"Je la garde précieusement.": "I’ll keep it safe.",
"Elle est belle, celle-là.": "That one’s beautiful.",
"Une étoile de plus.": "One more star.",
"Tu as beaucoup à dire…": "You have a lot to say…",
"Prends ton temps.": "Take your time.",
"Tes objets": "Your items",
"Tu n’as encore rien débloqué.": "You haven’t unlocked anything yet.",
"Les couleurs, les yeux, les accessoires, la taille et la magie se débloqueront dans la boutique, avec la poussière d’étoiles que tu gagnes en écrivant.": "Colours, eyes, accessories, size and magic will unlock in the shop, with the stardust you earn by writing.",
"Personnaliser ma lueur": "Customise my glow",
"creature mascotte couleur accessoire chapeau lunettes yeux taille objets": "creature mascot colour accessory hat glasses eyes size items",
"Personnalisation": "Customisation",
"ciel ambiance planetes lune aurores brume": "sky ambience planets moon auroras mist",
"Ambiance, astres et animations débloqués": "Unlocked ambience, celestial bodies and animations",
"La boutique et ta lueur": "The shop and your glow",
"Ce que tu as débloqué dans la boutique": "What you’ve unlocked in the shop",
// v11 : tout se débloque avec la poussière d'étoiles (boutique à onglets, catalogue, « Personnaliser mon ciel »)
"Ta lueur": "Your glow",
"Ton ciel": "Your sky",
"Personnaliser mon ciel": "Customise my sky",
"Encore ✦{n} à gagner en écrivant.": "✦{n} more to earn by writing.",
"Porté": "Wearing",
"Choisi": "Chosen",
"À toi": "Yours",
"Débloqué": "Unlocked",
"Pour commencer": "To begin",
"Un premier cadeau, pour ✦10.": "A first gift, for ✦10.",
"Tu gagnes ✦10 chaque jour où tu écris. Touche un objet à toi pour le porter, l’allumer ou le régler.": "You earn ✦10 every day you write. Tap an item you own to wear it, switch it on or adjust it.",
"Ciel {nom}, à débloquer pour ✦{prix}": "{nom} sky, unlock it for ✦{prix}",
"Lumière": "Light",
"Tout est débloqué pour ton ciel.": "Everything is unlocked for your sky.",
"Encore {n} chose à débloquer pour ton ciel dans la boutique.": "{n} more thing to unlock for your sky in the shop.",
"Encore {n} choses à débloquer pour ton ciel dans la boutique.": "{n} more things to unlock for your sky in the shop.",
"Tout est débloqué pour ta lueur.": "Everything is unlocked for your glow.",
"Encore {n} chose à débloquer pour ta lueur dans la boutique.": "{n} more thing to unlock for your glow in the shop.",
"Encore {n} choses à débloquer pour ta lueur dans la boutique.": "{n} more things to unlock for your glow in the shop.",
"Ronde": "Round",
"Lisse": "Smooth",
"Douce": "Gentle",
"Par défaut": "Default",
"Expression": "Expression",
"Mouvement": "Motion",
"À 0, le ciel reste immobile : plus d’ondes, de dérive ni de passages.": "At 0 the sky stays still: no more ripples, drifting or passing lights.",
"Silhouettes": "Shapes",
"Textures": "Textures",
"Visage": "Face",
"Accessoires": "Accessories",
"Habits": "Clothes",
"Membres": "Limbs",
"Ambiances": "Skies",
"Astres": "Celestial bodies",
"Animations": "Animations",
"Silhouette chat": "Cat shape",
"Des oreilles pointues et une petite queue.": "Pointy ears and a little tail.",
"Silhouette fantôme": "Ghost shape",
"Un bas en vagues qui ondule doucement.": "A wavy hem that ripples gently.",
"Silhouette cœur": "Heart shape",
"Ta lueur prend la forme d’un cœur.": "Your glow takes the shape of a heart.",
"Silhouette étoile": "Star shape",
"Cinq branches arrondies, toutes douces.": "Five soft, rounded points.",
"Nacre": "Mother-of-pearl",
"Des reflets irisés, comme une perle.": "Iridescent glints, like a pearl.",
"Givre": "Frost",
"Une surface glacée qui scintille.": "An icy surface that sparkles.",
"Paillettes": "Glitter",
"De minuscules éclats qui pétillent.": "Tiny flecks that fizz with light.",
"Nébuleuse": "Nebula",
"Un petit ciel qui tourbillonne à l’intérieur.": "A little sky swirling inside.",
"Couleur de la lueur": "Glow colour",
"Choisis sa teinte, ou laisse-la suivre ton humeur.": "Choose its hue, or let it follow your mood.",
"Rieuse": "Laughing",
"Des yeux plissés de bonheur.": "Eyes crinkled with happiness.",
"Rêveuse": "Dreamy",
"Un regard doux, à demi fermé.": "A soft, half-closed gaze.",
"Malicieuse": "Mischievous",
"Un clin d’œil et un sourire en coin.": "A wink and a crooked smile.",
"Étonnée": "Amazed",
"De grands yeux ronds et une petite bouche.": "Big round eyes and a little mouth.",
"Couleur des yeux": "Eye colour",
"Des yeux de la couleur de ton choix.": "Eyes in the colour of your choice.",
"Taille des yeux": "Eye size",
"Petits, normaux ou grands.": "Small, normal or large.",
"Un halo qui flotte au-dessus de sa tête.": "A halo floating above its head.",
"Une tige fine et une petite lanterne.": "A thin stalk and a little lantern.",
"De petites lunettes rondes.": "Little round glasses.",
"Couronne d’étoiles": "Crown of stars",
"Trois étoiles qui flottent.": "Three floating stars.",
"Chapeau de magicien": "Wizard’s hat",
"Pointu et étoilé.": "Pointy and starry.",
"Pour l’accessoire que tu portes.": "For the accessory you’re wearing.",
"Écharpe": "Scarf",
"Une écharpe douce nouée sous le visage.": "A soft scarf tied under its face.",
"Nœud papillon": "Bow tie",
"Un petit nœud bien mis.": "A neat little bow.",
"Cape": "Cape",
"Une cape de lumière qui flotte derrière elle.": "A cape of light floating behind it.",
"Petites ailes": "Little wings",
"Des ailes de lumière qui battent.": "Fluttering wings of light.",
"Petits bras": "Little arms",
"Pour faire coucou.": "For waving hello.",
"Petits pieds": "Little feet",
"Deux petits pieds qui pendent.": "Two little dangling feet.",
"Plus petite ou plus grande.": "Smaller or bigger.",
"Elle sème de petites étincelles.": "It scatters little sparks.",
"Ciel Aube": "Dawn sky",
"Un ciel rose et violet, comme au petit matin.": "A pink and violet sky, like early morning.",
"Ciel Océan": "Ocean sky",
"Un ciel bleu profond, comme sous la mer.": "A deep blue sky, like under the sea.",
"Ciel Papier": "Paper sky",
"Un ciel clair, comme une page de carnet.": "A pale sky, like a notebook page.",
"Les nébuleuses deviennent des nuages épais.": "The nebulae become thick clouds.",
"Tes étoiles se mettent à scintiller.": "Your stars begin to twinkle.",
"Le ciel tourne lentement sur lui-même.": "The sky slowly turns on itself.",
"Réglages de lumière": "Light settings",
"Lueur, profondeur de champ et effet cinéma.": "Glow, depth of field and cinema effect.",
"Couleurs des humeurs": "Mood colours",
"Choisis la couleur de chaque humeur.": "Choose the colour of each mood.",
"La Lune": "The Moon",
"La vraie lune du jour, avec sa phase.": "Today’s real moon, with its phase.",
"Planète à anneaux": "Ringed planet",
"Une planète dorée et ses anneaux, au loin.": "A golden planet and its rings, far away.",
"Planète océan": "Ocean planet",
"Une planète bleue aux nuages blancs.": "A blue planet with white clouds.",
"Géante rouge": "Red giant",
"Une énorme planète rousse, à l’horizon.": "A huge russet planet on the horizon.",
"Voie lactée": "Milky Way",
"Une grande bande de lumière au loin.": "A great band of light in the distance.",
"Poussière d’étoiles": "Stardust",
"Un voile de poussière qui traverse le ciel.": "A veil of dust drifting across the sky.",
"Étoiles filantes": "Shooting stars",
"Elles traversent ton ciel de temps en temps.": "They cross your sky now and then.",
"Satellites": "Satellites",
"Un petit point qui clignote et passe.": "A little blinking dot passing by.",
"Lucioles": "Fireflies",
"De petites étincelles qui tournent autour de tes étoiles.": "Little sparks circling your stars.",
"Comètes": "Comets",
"Une longue queue de lumière, de temps en temps.": "A long tail of light, now and then.",
"Dessins d’étoiles": "Star drawings",
"Parfois, les étoiles dessinent une forme.": "Sometimes the stars draw a shape.",
"Aurores boréales": "Northern lights",
"Un rideau de lumière ondule dans le ciel.": "A curtain of light ripples across the sky.",
"Baleine d’étoiles": "Star whale",
"Une baleine de lumière nage au loin.": "A whale of light swims in the distance."
};

export const EN_HTML = {
"aide-liste": "\n    <li><b>Pinch</b> or <b>scroll</b>: zoom from years down to a single day</li>\n    <li><b>Tap</b> a nebula or a star to dive into it</li>\n    <li><b>+</b> at the bottom: write · <b>◎</b> on the right: back to today</li>\n    <li><b>Drag</b> to rotate · <b>two fingers</b> to move</li>\n    <li><b>⋯</b>: the menu</li>\n  ",
"aide-exemples": "This sky contains <b>example entries</b>, made up to show you what it looks like. None of it is yours: clear them whenever you like, here or later with <b>⋯</b> → <i>Settings</i>."
};
