// English translation. The key is the French text used in the code (see langue.js).
export const EN = {
// v9 : accueil raconté, boutique, ciel qui se construit, journal seul
"Bienvenue dans ton univers.": "Welcome to your universe.",
"Pour l’instant, il est vide. C’est à toi de le construire, une pensée à la fois.": "For now, it’s empty. It’s yours to build, one thought at a time.",
"Commencer": "Begin",
"Voici ta lueur.": "This is your glow.",
"Elle t’accompagne et grandit avec toi. Comment veux-tu l’appeler ?": "It keeps you company and grows with you. What will you call it?",
"Un prénom": "A name",
"Continuer": "Continue",
"Je choisirai plus tard": "I’ll choose later",
"Touche + pour écrire ta journée. Tu peux y glisser une photo.": "Tap + to write your day. You can add a photo too.",
"Ta première étoile.": "Your first star.",
"Chaque jour où tu écris en allume une nouvelle. Sa couleur, c’est ton humeur.": "Each day you write lights a new one. Its colour is your mood.",
"Ta poussière d’étoiles.": "Your stardust.",
"Tu en gagnes chaque jour où tu écris. Elle sert à personnaliser ta lueur et ton ciel, dans la boutique.": "You earn some every day you write. Use it in the shop to customise your glow and your sky.",
"Ouvrir la boutique": "Open the shop",
"Ton univers commence ici.": "Your universe starts here.",
"Reviens demain pour une nouvelle étoile. La boutique, tes réglages et la langue sont dans ⋯.": "Come back tomorrow for a new star. The shop, your settings and the language are in ⋯.",
"C’est parti": "Let’s go",
"+ ✦{n} poussière d’étoiles": "+ ✦{n} stardust",
"Passer": "Skip",
"Allumé": "On",
"Éteint": "Off",
"Tu gagnes ✦10 chaque jour où tu écris. Un objet acheté se rallume ou s’éteint d’un toucher.": "You earn ✦10 every day you write. Tap an item you own to turn it on or off.",
"De nouveaux objets arrivent au fil des jours.": "New items arrive as the days go by.",
"Prochain : {nom}, dans {d}.": "Next: {nom}, in {d}.",
"Tu as écrit {n} jour.": "You have written on {n} day.",
"Tu as écrit {n} jours.": "You have written on {n} days.",
"Ta première étoile": "Your first star",
"Le jour où tu écris pour la première fois.": "The day you write for the first time.",
"Tes constellations": "Your constellations",
"Les jours écrits à la suite se relient par un fil de lumière.": "Days written in a row are joined by a thread of light.",
"La poussière d’étoiles": "Stardust",
"Un voile fin apparaît autour de tes étoiles.": "A fine veil appears around your stars.",
"Les nébuleuses": "The nebulae",
"Les mois et les semaines deviennent des nuages de lumière.": "Months and weeks become clouds of light.",
"Les étoiles filantes": "Shooting stars",
"Elles traversent ton ciel de temps en temps, avec d’autres surprises.": "They cross your sky now and then, along with other surprises.",
"La Voie lactée": "The Milky Way",
"Une grande bande de lumière se dessine au loin.": "A great band of light appears in the distance.",
"Les aurores": "The auroras",
"Un rideau de lumière ondule parfois dans le ciel.": "A curtain of light sometimes ripples across the sky.",
"Ta première galaxie": "Your first galaxy",
"Une année entière d’écriture. La suite arrive à ce moment-là.": "A whole year of writing. What comes next arrives then.",
"Yeux étoilés": "Starry eyes",
"Un reflet en étoile dans les yeux de ta lueur.": "A star-shaped sparkle in your glow’s eyes.",
"Croix de lumière": "Light crosses",
"Tes étoiles brillent avec de longues branches.": "Your stars shine with long rays.",
"Filantes dorées": "Golden shooting stars",
"Des étoiles filantes dorées, plus souvent.": "Golden shooting stars, more often.",
"Journée vide. Raconte-la.": "An empty day. Tell its story.",
"+ Écrire": "+ Write",
"Nouveau dans ton ciel : {nom}": "New in your sky: {nom}",
"nouvelle pensee journal intime photo video": "new thought journal diary photo video",
"Boutique": "Shop",
"poussiere etoiles acheter objets": "stardust buy items shop",
"Mon ciel": "My sky",
"paliers ciel grandir debloquer": "milestones sky grow unlock",
"Boutique, ton ciel, personnaliser ta lueur": "Shop, your sky, customise your glow",
"Des objets pour ta lueur et ton ciel": "Items for your glow and your sky",
"Ce qui pousse quand tu écris": "What grows when you write",
"+ Photo ou vidéo": "+ Photo or video",
"Le mois": "The month",
"Photo ou vidéo": "Photo or video",
"Menu": "Menu",
"‹ Menu": "‹ Menu",
"Chercher une commande ou une pensée": "Search a command or a thought",
"Ta petite lueur : la personnaliser, un souvenir": "Your little glow: customise it, a memory",
"Personnaliser": "Customise",
"Couleur, yeux, accessoire, taille": "Colour, eyes, accessory, size",
"Elle va relire une ancienne pensée": "It will reread an old thought",
"Renommer": "Rename",
"La boutique, les quêtes du jour et le chemin arriveront ici.": "The shop, daily quests and the path will arrive here.",
"Suivi": "Tracking",
"Tes humeurs sur 30 jours et le résumé du mois": "Your moods over 30 days and the month summary",
"Filtres": "Filters",
"Filtre actif : #{tag}": "Active filter: #{tag}",
"Ne montrer que les jours d’un #mot": "Only show the days of a #word",
"Écris un #mot dans une entrée (par exemple #famille) : il deviendra un filtre.": "Write a #word in an entry (for example #family): it will become a filter.",
"Rappel du soir, langue, sauvegarde, aide": "Evening reminder, language, backup, help",
"Mes données": "My data",
"Aide": "Help",
"Calme": "Calm",
"Joie": "Joy",
"Élan": "Drive",
"Mélancolie": "Melancholy",
"Tempête": "Storm",
"calme": "calm",
"joie": "joy",
"élan": "drive",
"mélancolie": "melancholy",
"tempête": "storm",
"Journal": "Journal",
"Note": "Note",
"Notes": "Notes",
"Tâche": "Task",
"Tâches": "Tasks",
"Média": "Media",
"Médias": "Media",
"Nuit": "Night",
"Aube": "Dawn",
"Océan": "Ocean",
"Papier": "Paper",
"hiver": "winter",
"printemps": "spring",
"été": "summer",
"automne": "autumn",
"Votre journal : une étoile par jour": "Your journal: one star per day",
"Position dans le temps": "Position in time",
"Retirer le filtre": "Remove the filter",
"Journée": "Day",
"Jour précédent": "Previous day",
"Jour suivant": "Next day",
"Date qui compte": "Date that matters",
"Marquer une date qui compte": "Mark a date that matters",
"Fermer la journée": "Close the day",
"Nouvelle entrée": "New entry",
"Type d’entrée": "Entry type",
"Fermer (le brouillon est gardé)": "Close (the draft is kept)",
"Mise en forme": "Formatting",
"Titre 1": "Heading 1",
"Titre 2": "Heading 2",
"Titre 3": "Heading 3",
"+ Ajouter": "+ Add",
"Ajouter un bloc": "Add a block",
"ou tapez / en début de ligne": "or type / at the start of a line",
"Liste à puces": "Bulleted list",
"Liste numérotée": "Numbered list",
"Texte simple": "Plain text",
"Titre 4": "Heading 4",
"Citation": "Quote",
"Séparateur": "Divider",
"Image": "Image",
"Vidéo": "Video",
"Texte": "Text",
"Fermer le clavier": "Close keyboard",
"Fichier trop lourd (150 Mo maximum)": "File too large (150 MB maximum)",
"Fermer": "Close",
"Qu’est-ce qui traverse ?": "What’s on your mind?",
"Jour": "Day",
"Jour de l’entrée": "Day of the entry",
"Humeur du jour": "Mood of the day",
"Titre (facultatif)": "Title (optional)",
"Titre de la note": "Note title",
"Écrivez. Ce texte ne quitte jamais cet appareil.": "Write. This text never leaves this device.",
"Prendre une photo": "Take a photo",
"Choisir dans la galerie": "Choose from gallery",
"Dicter à la voix": "Dictate by voice",
"Dicter": "Dictate",
"Annuler": "Cancel",
"Enregistrer": "Save",
"Une date qui compte": "A date that matters",
"Anniversaire de…, départ, rendez-vous…": "…’s birthday, a departure, an appointment…",
"Titre": "Title",
"Chaque année": "Every year",
"Retirer": "Remove",
"Marquer": "Mark",
"Personnaliser la lueur": "Customise the glow",
"Ma lueur": "My glow",
"Nommer la petite lueur": "Name the little glow",
"Une petite lueur vous a trouvé.": "A little glow has found you.",
"Comment voulez-vous l’appeler ?": "What would you like to call it?",
"Lueur": "Glow",
"Nom de la lueur": "Name of the glow",
"Adopter": "Adopt",
"Comment voyager dans le ciel": "How to travel through the sky",
"Voyager dans le temps": "Travel through time",
"Effacer les exemples": "Clear the examples",
"Compris": "Got it",
"Analyses": "Insights",
"Réglages": "Settings",
"Arrêter": "Stop",
"Écrire": "Write",
"Écrire (N)": "Write (N)",
"Commandes": "Commands",
"Commandes ( / )": "Commands ( / )",
"commandes": "commands",
"Aller à aujourd’hui": "Go to today",
"aujourd’hui": "today",
"Aujourd’hui": "Today",
"Zoom dans le temps": "Zoom through time",
"Plonger d’un niveau": "Dive one level",
"Plonger (zoom avant)": "Dive (zoom in)",
"Remonter d’un niveau": "Go up one level",
"Remonter (zoom arrière)": "Go up (zoom out)",
"une commande, ou une idée à retrouver…": "a command, or an idea to find…",
"Commande ou recherche": "Command or search",
"choisir ·": "choose ·",
"valider ·": "confirm ·",
"fermer": "close",
"échap": "esc",
"Sens profond : non": "Deep meaning: no",
"Noms": "Names",
"Sauvegarde : non": "Backup: no",
"Exporter": "Export",
"Importer": "Import",
"Installer l’appli": "Install the app",
"Effacer les entrées d’exemple": "Clear the example entries",
"Entrée inventée pour l’exemple": "Made-up entry, just an example",
"exemple": "example",
"exemples": "examples",
"Voir toutes les entrées #{tag}": "See all entries #{tag}",
"Modifier": "Edit",
"modifier": "edit",
"Supprimer": "Delete",
"supprimer": "delete",
"Modifier la tâche": "Edit the task",
"Supprimer la tâche": "Delete the task",
"Ouvrir {nom}": "Open {nom}",
"le média": "the media",
"introuvable": "not found",
"Modifier cette date": "Edit this date",
"{n} an": "{n} year",
"{n} ans": "{n} years",
"Couleur libre": "Free colour",
"couleur libre": "free colour",
"humeur ?": "mood?",
"Journée vide. Ajoutez une première entrée.": "Empty day. Add a first entry.",
"éclaircie": "clear",
"orage": "storm",
"{n} j": "{n} d",
"Météo intérieure": "Inner weather",
"Bilan du mois": "Month in review",
"{n} jours": "{n} days",
"{n} jour": "{n} day",
"Courbe de l’humeur dans le temps": "Mood curve over time",
"Mois précédent": "Previous month",
"Mois suivant": "Next month",
"Bilan": "Review",
"Survoler le mois": "Fly over the month",
"Aucune pensée sur cette période : le ciel est vide.": "No thoughts in this period: the sky is empty.",
"plutôt dégagé": "mostly clear",
"variable": "changeable",
"nuageux": "cloudy",
"orageux": "stormy",
"Ciel {ciel}. {a}, {b}, {c} sur {n}.": "Sky {ciel}. {a}, {b}, {c} out of {n}.",
"{n} éclaircie": "{n} clear spell",
"{n} éclaircies": "{n} clear spells",
"{n} orage": "{n} storm",
"{n} orages": "{n} storms",
"{n} jour écrit": "{n} day written",
"{n} jours écrits": "{n} days written",
"lumineux": "bright",
"porté par l’élan": "carried by drive",
"voilé de mélancolie": "veiled in melancholy",
"agité": "restless",
"Aucune pensée ce mois-ci.": "No thoughts this month.",
"{a} sur {b}.": "{a} over {b}.",
"{n} pensée": "{n} thought",
"{n} pensées": "{n} thoughts",
"Le ciel a été surtout {adj} ({liste}).": "The sky was mostly {adj} ({liste}).",
"La seconde moitié du mois s’éclaircit.": "The second half of the month brightens.",
"La seconde moitié du mois s’assombrit.": "The second half of the month darkens.",
"Le mois est resté d’une humeur stable.": "The month stayed in a steady mood.",
"Reviennent souvent : {mots}.": "Often recurring: {mots}.",
"Le jour le plus lumineux : {d}.": "The brightest day: {d}.",
"{quand} : rien d’écrit pour l’instant.": "{quand}: nothing written yet.",
"{quand} : {n} sur {total}": "{quand}: {n} out of {total}",
"plutôt lumineuse": "rather bright",
"plus lourde que d’habitude": "heavier than usual",
"en équilibre": "balanced",
", surtout {humeur} ({ton}).": ", mostly {humeur} ({ton}).",
"semaine du {d}": "week of {d}",
"Semaine du {d}": "Week of {d}",
"Cette semaine": "This week",
"Ce mois-ci": "This month",
"En {mois}": "In {mois}",
"Série actuelle : {a} · record : {r}": "Current streak: {a} · record: {r}",
"Années": "Years",
"série de {n} jours": "{n}-day streak",
"Matière": "Texture",
"Brume": "Haze",
"Scintillement": "Twinkle",
"Animation du ciel": "Sky animation",
"Rotation": "Rotation",
"Optique": "Optics",
"Profondeur de champ": "Depth of field",
"Cinéma": "Cinema",
"Ciel {nom}": "{nom} sky",
"Ciel": "Sky",
"Humeurs": "Moods",
"rétablir": "reset",
"nommer cette ambiance": "name this look",
"Nom du look": "Look name",
"Looks": "Looks",
"Activé": "On",
"Désactivé": "Off",
"Heure du rappel": "Reminder time",
"Ce navigateur ne gère pas les notifications : le rappel apparaît dans l’appli quand elle est ouverte.": "This browser doesn’t support notifications: the reminder shows up in the app while it’s open.",
"Notifications autorisées. Le rappel s’affiche si rien n’est écrit ce jour-là.": "Notifications allowed. The reminder appears if nothing has been written that day.",
"Notifications bloquées dans le navigateur : le rappel n’apparaît que dans l’appli ouverte.": "Notifications blocked in the browser: the reminder only appears in the open app.",
"Au premier activage, le navigateur vous demande l’autorisation.": "The first time you turn it on, the browser asks for permission.",
"Rappel du soir": "Evening reminder",
"Rappel quotidien": "Daily reminder",
"Heure": "Time",
"envoyer un test": "send a test",
"Appli fermée : il faut l’avoir installée (Chrome, Edge, Android) ; sur iPhone, ajoutez-la d’abord à l’écran d’accueil.": "App closed: it must be installed (Chrome, Edge, Android); on iPhone, add it to the Home Screen first.",
"Aucun": "None",
"Anneau": "Ring",
"Antenne": "Antenna",
"Lunettes": "Glasses",
"Couronne": "Crown",
"Chapeau": "Hat",
"Petits": "Small",
"Normaux": "Normal",
"Grands": "Large",
"Suit mon humeur": "Follows my mood",
"Couleur : suit mon humeur": "Colour: follows my mood",
"Couleur": "Colour",
"Couleurs": "Colours",
"Se déplacer dans le ciel": "Move around the sky",
"Se déplacer": "Move around",
"Texte de l’entrée": "Entry text",
"ou tapez / au début d’une ligne": "or type / at the start of a line",
"Accessoire": "Accessory",
"Couleur de l’accessoire": "Accessory colour",
"Yeux": "Eyes",
"Taille": "Size",
"Magie": "Magic",
"Étincelles": "Sparkles",
"Changer de nom": "Change name",
"Chercher « {q} » dans mes pensées": "Search “{q}” in my thoughts",
"Écrire dans le journal": "Write in the journal",
"nouvelle pensee journal intime": "new thought journal diary write",
"Nouvelle note": "New note",
"note idee travail": "note idea work",
"Nouvelles tâches": "New tasks",
"tache todo liste faire travail": "task todo list work",
"Ajouter une photo ou une vidéo": "Add a photo or a video",
"media image photo video": "media image photo video",
"maintenant jour present etoile": "now day present star today",
"Personnaliser ma petite lueur": "Customize my little glow",
"creature mascotte couleur accessoire chapeau lunettes yeux taille": "creature mascot glow colour accessory hat glasses eyes size",
"anniversaire evenement important date etoile doree": "birthday anniversary event important date golden star",
"Prochaine date qui compte": "Next date that matters",
"anniversaire evenement a venir": "birthday anniversary event upcoming",
"Aucune date marquée. Ouvrez un jour, puis ☆.": "No date marked yet. Open a day, then ☆.",
"etiquette tag filtre": "label tag filter",
"Retirer le filtre #{tag}": "Remove the filter #{tag}",
"etiquette filtre effacer": "label tag filter clear",
"Vue d’ensemble : toutes les années": "Overview: all years",
"dezoomer annees general": "zoom out years overview",
"dezoomer parent": "zoom out up parent",
"notification rappel rituel heure": "notification reminder ritual time evening",
"humeur courbe analyses ciel": "mood curve insights sky weather",
"analyses resume survol mois": "insights summary review month",
"apparence lumiere couleurs looks optique": "settings appearance light colours looks optics",
"Masquer les noms des mois et des années": "Hide the names of months and years",
"Afficher les noms des mois et des années": "Show the names of months and years",
"noms etiquettes": "names labels",
"Ciel : {nom}": "Sky: {nom}",
"theme ambiance": "theme mood sky",
"actuel": "current",
"Sens profond": "Deep meaning",
"modele langage ia comprendre": "model language ai understand meaning",
"oui": "yes",
"non": "no",
"Sauvegarde automatique": "Automatic backup",
"dossier copie backup": "folder copy backup save",
"Sauvegarde": "Backup",
"reconnecter": "reconnect",
"Exporter le journal": "Export the journal",
"telecharger json": "download json export",
"Importer un journal": "Import a journal",
"fichier json": "file json import",
"exemples demo fictives": "examples demo sample fake clear",
"Installer l’application": "Install the app",
"Raconte-moi un souvenir": "Tell me a memory",
"souvenir ancienne pensee rappel creature lueur": "memory old thought remember creature glow",
"Pas encore de souvenir à portée de ciel.": "No memory within reach of the sky yet.",
"Appeler {nom}": "Call {nom}",
"la petite lueur": "the little glow",
"creature lueur venir": "creature glow come call",
"Renommer la petite lueur": "Rename the little glow",
"creature nom lueur": "creature name glow rename",
"Laisser la petite lueur dormir (la masquer)": "Let the little glow sleep (hide it)",
"Réveiller la petite lueur": "Wake the little glow",
"creature masquer afficher": "creature hide show glow",
"Elle est de retour.": "It’s back.",
"Aide : comment voyager dans le ciel": "Help: how to travel through the sky",
"aide tutoriel zoom comment": "help tutorial zoom how",
"Surprends-moi": "Surprise me",
"surprise hasard comete aurore baleine easter egg": "surprise random comet aurora whale easter egg",
"Plein écran": "Full screen",
"Quitter le plein écran": "Exit full screen",
"immersif": "immersive fullscreen",
"{n} entrée": "{n} entry",
"{n} entrées": "{n} entries",
"Aucune entrée avec #{tag}": "No entries with #{tag}",
"Aujourd’hui : {titre} !": "Today: {titre}!",
"{n} jours d’affilée. Continue !": "{n} days in a row. Keep going!",
"C’est ton record de série !": "That’s your best streak!",
"Et si on racontait aujourd’hui ?": "How about telling today’s story?",
"Dans {n} : {titre}.": "In {n}: {titre}.",
"Il fait froid dehors, pas ici.": "It’s cold outside, not in here.",
"Ça sent le printemps.": "Spring is in the air.",
"Les nuits d’été sont les plus douces.": "Summer nights are the sweetest.",
"J’aime l’automne et ses couleurs.": "I love autumn and its colours.",
"Supprimer ce média ?": "Delete this media?",
"Supprimer cette entrée ?": "Delete this entry?",
"une petite lueur": "a little glow",
"journée vide, cliquez pour écrire": "empty day, click to write",
"rien d’écrit": "nothing written",
"Choisir n’importe quelle couleur": "Pick any colour",
"Libre": "Free",
"Une note, une idée, une information": "A note, an idea, some information",
"Ce qu’il y a à faire": "Things to do",
"Des photos ou des vidéos pour cette journée": "Photos or videos for this day",
"Le contenu de la note… (#etiquette pour la retrouver)": "The note itself… (#label to find it again)",
"Une tâche par ligne": "One task per line",
"Une légende (facultatif)": "A caption (optional)",
"Brouillon retrouvé.": "Draft recovered.",
"Cristalliser": "Crystallize",
"Ajouter": "Add",
"Écrivez au moins quelques mots.": "Write at least a few words.",
"Une tâche par ligne.": "One task per line.",
"Une note vide ne dit rien.": "An empty note says nothing.",
"Choisissez au moins une photo ou une vidéo.": "Choose at least one photo or video.",
"Enregistrement des médias…": "Saving media…",
"Fichier": "File",
"La dictée utilise la reconnaissance vocale de votre navigateur : avec Chrome ou Edge, le son est envoyé à leurs serveurs pour être transcrit. Ce que vous écrivez au clavier, lui, reste sur votre appareil.": "Dictation uses your browser’s speech recognition: with Chrome or Edge, the audio is sent to their servers to be transcribed. What you type on the keyboard stays on your device.",
"Activer la dictée ?": "Turn on dictation?",
"Micro refusé : autorisez-le dans le navigateur.": "Microphone blocked: allow it in the browser.",
"Dictée indisponible ({e}).": "Dictation unavailable ({e}).",
"Arrêter la dictée": "Stop dictation",
"Télécharger un petit modèle de langage (≈120 Mo) pour mieux comprendre le sens ? Il s’exécute sur votre appareil, vos textes ne sont pas envoyés.": "Download a small language model (≈120 MB) to better understand meaning? It runs on your device; your texts are not sent anywhere.",
"Recalcul…": "Recalculating…",
"Modèle indisponible : on reste en mode léger.": "Model unavailable: staying in light mode.",
"Effacer les entrées d’exemple ?": "Clear the example entries?",
"Exemples effacés. Le ciel est à vous.": "Examples cleared. The sky is yours.",
"{n} vidéo ou fichier non inclus dans l’export (trop lourd).": "{n} video or file not included in the export (too large).",
"{n} vidéos ou fichiers non inclus dans l’export (trop lourds).": "{n} videos or files not included in the export (too large).",
"Fichier non reconnu.": "File not recognised.",
"Pour tester, activez d’abord le rappel et autorisez les notifications.": "To test, first turn on the reminder and allow notifications.",
"Sauvegarde reprise.": "Backup resumed.",
"Arrêter la sauvegarde automatique ? Les fichiers déjà écrits restent dans le dossier.": "Stop automatic backup? Files already written stay in the folder.",
"Sauvegarde dans « {nom} » (les photos et vidéos n’y sont pas copiées).": "Backing up to “{nom}” (photos and videos are not copied there).",
"Sauvegarde impossible : {e}": "Backup failed: {e}",
"Sauvegarde interrompue : reconnectez le dossier.": "Backup interrupted: reconnect the folder.",
"Constellation est installée.": "Constellation is installed.",
"{nom} vous attend : une pensée pour ce soir ?": "{nom} is waiting: a thought for tonight?",
"Votre lueur": "Your glow",
"Le jour s’éteint… une pensée pour ce soir ?": "The day is fading… a thought for tonight?",
"Une pensée pour ce soir ?": "A thought for tonight?",
"Bienvenue, {nom}.": "Welcome, {nom}.",
"Ce navigateur ne gère pas les notifications. Le rappel ne s’affichera que dans l’appli ouverte.": "This browser doesn’t support notifications. The reminder will only show in the open app.",
"Notifications refusées par le navigateur : le rappel ne s’affichera que dans l’appli ouverte.": "Notifications refused by the browser: the reminder will only show in the open app.",
"Rappel activé à {h}.": "Reminder set for {h}.",
"Rappel désactivé.": "Reminder turned off.",
"Stockage indisponible": "Storage unavailable",
"Type de fichier non pris en charge": "File type not supported",
"Vidéo trop lourde (150 Mo maximum)": "Video too large (150 MB maximum)",
"Chargement du modèle…": "Loading the model…",
"Modèle {p} %": "Model {p}%",
"{nom} a grandi.": "{nom} has grown.",
"J’ai grandi !": "I’ve grown!",
"Bonjour ! Moi, c’est {nom}.": "Hello! I’m {nom}.",
"hier": "yesterday",
"il y a {n} jours": "{n} days ago",
"Ça me fait plaisir !": "That makes me happy!",
"Oh, c’est beau.": "Oh, that’s beautiful.",
"Ça me touche.": "That touches me.",
"Je suis là.": "I’m here.",
"Courage…": "Hang in there…",
"Respire doucement.": "Breathe gently.",
"Oh… regarde là-haut.": "Oh… look up there.",
"Oh !": "Oh!",
"Miaou ?": "Meow?",
"Hm ? Oh, tu es là.": "Hm? Oh, you’re here.",
"Je t’écoute.": "I’m listening.",
"Alors, cette journée ?": "So, how was today?",
"Raconte-moi.": "Tell me.",
"Lalala~": "Lalala~",
"Tu danses avec moi ?": "Dance with me?",
"Tu m’avais manqué.": "I missed you.",
"Les étoiles brillent plus fort la nuit.": "The stars shine brighter at night.",
"Chut… écoute le ciel.": "Shh… listen to the sky.",
"Je me demande ce que tu vas écrire.": "I wonder what you’ll write.",
"Tu vois cette étoile ? C’est une journée.": "See that star? It’s a day.",
"Un petit tour ?": "A little tour?",
"Je suis bien, ici.": "I like it here.",
"Wouiii !": "Wheee!",
"Tout effacer et recommencer": "Erase everything and start over",
"Tout effacer ? Ton journal, tes photos, ta lueur, ta poussière d’étoiles et tes réglages seront supprimés de cet appareil. Exporte d’abord le journal si tu veux en garder une copie.": "Erase everything? Your journal, photos, glow, stardust and settings will be deleted from this device. Export your journal first if you want to keep a copy.",
"Dernière vérification : cette action est définitive. Tout effacer et recommencer ?": "Last check: this cannot be undone. Erase everything and start over?",
"Un petit rappel ?": "A little reminder?",
"Ta lueur peut te faire signe chaque jour, à l’heure de ton choix, pour écrire ta journée.": "Your glow can nudge you every day, at a time you choose, to write about your day.",
"Chaque jour à": "Every day at",
"Activer le rappel": "Turn on the reminder",
"Non merci": "No thanks",
"Comme une appli.": "Just like an app.",
"Ajoute Constellation à ton écran d’accueil : elle s’ouvrira en plein écran, sans la barre du navigateur, avec plus de place pour écrire.": "Add Constellation to your home screen: it will open full screen, without the browser bar, with more room to write.",
"Touche Partager, puis « Sur l’écran d’accueil ».": "Tap Share, then “Add to Home Screen”.",
"Menu ⋮ du navigateur, puis « Ajouter à l’écran d’accueil ».": "Browser menu ⋮, then “Add to Home screen”.",
"Ajouter à l’écran d’accueil": "Add to home screen",
"Plus tard": "Later",
"+ Ajouter un média": "+ Add media",
"jours écrits": "days written",
"humeur dominante": "main mood",
"ciel moyen": "average sky",
"Le fil des jours": "Day by day",
"Répartition": "Breakdown",
"En résumé": "In short",
"Aucune humeur sur cette période.": "No moods in this period.",
"Choisis une humeur en écrivant : elle apparaîtra ici.": "Pick a mood when you write: it will show up here.",
"Écrire maintenant": "Write now",
"dégagé": "clear",
"L M M J V S D": "M T W T F S S",
"Aaaah…": "Aaaah…",
"*bâille*": "*yawns*",
"Je somnole un peu…": "I'm getting a little sleepy…",
"J’ai le tournis…": "I'm dizzy…",
"Ouh là, ça tourne !": "Whoa, it's spinning!",
"Tout tourne…": "Everything's spinning…",
"Hé !": "Hey!",
"Doucement !": "Easy!",
"Tu m’as fait peur !": "You scared me!",
"On plonge ?": "Shall we dive?",
"Ça tourne !": "It’s spinning!",
"Haaaa !": "Whoaaa!",
"Vite, un vœu !": "Quick, make a wish!",
"Hihi.": "Hehe.",
"Encore !": "Again!",
"Mmh…": "Mmm…",
"Oh, ça chatouille !": "Oh, that tickles!",
"Merci.": "Thank you.",
"Me voilà !": "Here I am!",
"Aaah !": "Aaah!",
"Waouh !": "Wow!",
"Une baleine ?!": "A whale?!",
"La lune…": "The moon…",
"Je la garde précieusement.": "I’ll keep it safe.",
"Elle est belle, celle-là.": "That one’s beautiful.",
"Une étoile de plus.": "One more star.",
"Tu as beaucoup à dire…": "You have a lot to say…",
"Ce navigateur ne sait pas dicter : touche le micro de ton clavier, ou ouvre Constellation dans Chrome.": "This browser can’t dictate: tap your keyboard’s mic, or open Constellation in Chrome.",
"Hé, je lisais !": "Hey, I was reading!",
"Tu m’as surprise !": "You startled me!",
"Mmh… continue.": "Mmm… keep going.",
"Ça chatouille !": "That tickles!",
"J’aime bien te lire.": "I like reading you.",
"Ah, d’accord !": "Ah, I see!",
"Ah oui, je vois…": "Oh yes, I see…",
"Merci de me l’avoir confié.": "Thanks for telling me.",
"Je garde ça précieusement.": "I’ll keep it safe.",
"Oh ! Quelle journée.": "Oh! What a day.",
"Touche <b>Partager</b> (le carré avec une flèche), puis <b>« Sur l’écran d’accueil »</b>.": "Tap <b>Share</b> (the square with an arrow), then <b>“Add to Home Screen”</b>.",
"Dans Brave, ouvre le menu <b>⋮</b> (en bas ou en haut à droite), puis <b>« Ajouter à l’écran d’accueil »</b> ou <b>« Installer l’application »</b>.": "In Brave, open the <b>⋮</b> menu (bottom or top right), then <b>“Add to Home screen”</b> or <b>“Install app”</b>.",
"Touche le menu <b>≡</b> en bas à droite, puis <b>« Ajouter page à »</b> › <b>« Écran d’accueil »</b>.": "Tap the <b>≡</b> menu at the bottom right, then <b>“Add page to”</b> › <b>“Home screen”</b>.",
"Touche le menu <b>⋮</b>, puis <b>« Installer »</b> ou <b>« Ajouter à l’écran d’accueil »</b>.": "Tap the <b>⋮</b> menu, then <b>“Install”</b> or <b>“Add to Home screen”</b>.",
"Touche le menu <b>⋮</b> du navigateur, puis <b>« Ajouter à l’écran d’accueil »</b> ou <b>« Installer l’application »</b>.": "Tap the browser’s <b>⋮</b> menu, then <b>“Add to Home screen”</b> or <b>“Install app”</b>.",
"installer application appli raccourci": "install app shortcut home",
"C’est fait": "Done",
"D’abord, touche l’émotion qui colle à ta journée.": "First, tap the feeling that fits your day.",
"Maintenant, écris quelques mots sur ta journée.": "Now write a few words about your day.",
"Quand tu as fini, touche Cristalliser.": "When you’re done, tap Crystallize.",
"Salut, je suis ta lueur !": "Hi, I’m your glow!",
"Je vais t’accompagner et grandir avec toi. Comment veux-tu m’appeler ?": "I’ll keep you company and grow with you. What would you like to call me?",
"Regarde, ta première étoile !": "Look, your first star!",
"Chaque jour où tu écris, j’en allume une nouvelle. Sa couleur, c’est ton humeur.": "Every day you write, I light a new one. Its colour is your mood.",
"Et voici de la poussière d’étoiles.": "And here’s some stardust.",
"Tu en gagnes chaque jour où tu écris. Avec, tu peux me faire belle et décorer ton ciel, dans la boutique.": "You earn some every day you write. Use it in the shop to dress me up and decorate your sky.",
"Je peux te faire signe chaque jour, à l’heure de ton choix, pour qu’on écrive ta journée ensemble.": "I can give you a nudge every day, at a time you choose, so we write your day together.",
"Mets-moi sur ton écran d’accueil : je m’ouvrirai en plein écran, sans la barre du navigateur, avec plus de place pour écrire.": "Put me on your home screen: I’ll open full screen, without the browser bar, with more room to write.",
"Reviens demain, on allumera une nouvelle étoile. La boutique, les réglages et la langue sont dans ⋯. À demain !": "Come back tomorrow and we’ll light a new star. The shop, settings and language are in ⋯. See you tomorrow!",
"Forme": "Shape",
"Expressions": "Expressions",
"Effets": "Effects",
"Finitions": "Finishing touches",
"Rubriques": "Sections",
"Silhouette comète": "Comet shape",
"Une chevelure de lumière qui file derrière elle.": "A tail of light streaming behind her.",
"Aurore": "Aurora",
"Des voiles de lumière qui ondulent.": "Veils of light that ripple.",
"Espace profond": "Deep space",
"Un bout de nuit semé de minuscules étoiles.": "A piece of night sprinkled with tiny stars.",
"Soleil": "Sun",
"Une surface qui bouillonne de lumière.": "A surface bubbling with light.",
"Émerveillée": "Starstruck",
"Des étoiles à la place des yeux.": "Stars instead of eyes.",
"Curieuse": "Curious",
"De grands yeux pleins de reflets.": "Big eyes full of sparkle.",
"Ensommeillée": "Sleepy",
"Les paupières lourdes, toute paisible.": "Heavy eyelids, all peaceful.",
"Anneaux de planète": "Planet rings",
"Deux anneaux inclinés autour d’elle, comme Saturne.": "Two tilted rings around her, like Saturn.",
"Petite lune": "Little moon",
"Une lune qui tourne autour d’elle.": "A moon that circles around her.",
"Satellite": "Satellite",
"Il fait le tour d’elle, son feu clignote.": "It circles her, its light blinking.",
"Étoiles en orbite": "Orbiting stars",
"De petites étoiles tournent autour d’elle.": "Little stars circle around her.",
"Traînée de comète": "Comet trail",
"Une traînée de lumière quand elle file.": "A trail of light when she zooms.",
"Poudre d’étoiles": "Star powder",
"Une poussière dorée tombe doucement sous elle.": "Golden dust drifts down beneath her.",
"Prends ton temps.": "Take your time.",
"Tes objets": "Your items",
"Tu n’as encore rien débloqué.": "You haven’t unlocked anything yet.",
"Les couleurs, les yeux, les accessoires, la taille et la magie se débloqueront dans la boutique, avec la poussière d’étoiles que tu gagnes en écrivant.": "Colours, eyes, accessories, size and magic will unlock in the shop, with the stardust you earn by writing.",
"Personnaliser ma lueur": "Customise my glow",
"creature mascotte couleur accessoire chapeau lunettes yeux taille objets": "creature mascot colour accessory hat glasses eyes size items",
"Personnalisation": "Customisation",
"ciel ambiance planetes lune aurores brume": "sky ambience planets moon auroras mist",
"Ambiance, astres et animations débloqués": "Unlocked ambience, celestial bodies and animations",
"La boutique et ta lueur": "The shop and your glow",
"Ce que tu as débloqué dans la boutique": "What you’ve unlocked in the shop",
// v11 : tout se débloque avec la poussière d'étoiles (boutique à onglets, catalogue, « Personnaliser mon ciel »)
"Ta lueur": "Your glow",
"Ton ciel": "Your sky",
"Personnaliser mon ciel": "Customise my sky",
"Encore ✦{n} à gagner en écrivant.": "✦{n} more to earn by writing.",
"Porté": "Wearing",
"Choisi": "Chosen",
"À toi": "Yours",
"Débloqué": "Unlocked",
"Pour commencer": "To begin",
"Un premier cadeau, pour ✦10.": "A first gift, for ✦10.",
"Tu gagnes ✦10 chaque jour où tu écris. Touche un objet pour l’essayer, même s’il est trop cher. Touche un objet à toi pour le porter, l’allumer ou le régler.": "You earn ✦10 every day you write. Tap an item to try it, even if it costs too much. Tap an item you own to wear it, switch it on or adjust it.",
"Ciel {nom}, à débloquer pour ✦{prix}": "{nom} sky, unlock it for ✦{prix}",
"Lumière": "Light",
"Tout est débloqué pour ton ciel.": "Everything is unlocked for your sky.",
"Encore {n} chose à débloquer pour ton ciel dans la boutique.": "{n} more thing to unlock for your sky in the shop.",
"Encore {n} chose à débloquer pour tes planètes.": "{n} more thing to unlock for your planets.",
"Encore {n} choses à débloquer pour tes planètes.": "{n} more things to unlock for your planets.",
"Encore {n} choses à débloquer pour ton ciel dans la boutique.": "{n} more things to unlock for your sky in the shop.",
"Tout est débloqué pour ta lueur.": "Everything is unlocked for your glow.",
"Encore {n} chose à débloquer pour ta lueur dans la boutique.": "{n} more thing to unlock for your glow in the shop.",
"Encore {n} choses à débloquer pour ta lueur dans la boutique.": "{n} more things to unlock for your glow in the shop.",
"Ronde": "Round",
"Lisse": "Smooth",
"Douce": "Gentle",
"Par défaut": "Default",
"Expression": "Expression",
"Mouvement": "Motion",
"À 0, le ciel reste immobile : plus d’ondes, de dérive ni de passages.": "At 0 the sky stays still: no more ripples, drifting or passing lights.",
"Silhouettes": "Shapes",
"Textures": "Textures",
"Visage": "Face",
"Accessoires": "Accessories",
"Habits": "Clothes",
"Membres": "Limbs",
"Ambiances": "Skies",
"Astres": "Celestial bodies",
"Animations": "Animations",
"Silhouette chat": "Cat shape",
"Des oreilles pointues et une petite queue.": "Pointy ears and a little tail.",
"Silhouette fantôme": "Ghost shape",
"Un bas en vagues qui ondule doucement.": "A wavy hem that ripples gently.",
"Silhouette cœur": "Heart shape",
"Ta lueur prend la forme d’un cœur.": "Your glow takes the shape of a heart.",
"Silhouette étoile": "Star shape",
"Cinq branches arrondies, toutes douces.": "Five soft, rounded points.",
"Nacre": "Mother-of-pearl",
"Des reflets irisés, comme une perle.": "Iridescent glints, like a pearl.",
"Givre": "Frost",
"Une surface glacée qui scintille.": "An icy surface that sparkles.",
"Paillettes": "Glitter",
"De minuscules éclats qui pétillent.": "Tiny flecks that fizz with light.",
"Nébuleuse": "Nebula",
"Un petit ciel qui tourbillonne à l’intérieur.": "A little sky swirling inside.",
"Couleur de la lueur": "Glow colour",
"Choisis sa teinte, ou laisse-la suivre ton humeur.": "Choose its hue, or let it follow your mood.",
"Rieuse": "Laughing",
"Des yeux plissés de bonheur.": "Eyes crinkled with happiness.",
"Rêveuse": "Dreamy",
"Un regard doux, à demi fermé.": "A soft, half-closed gaze.",
"Malicieuse": "Mischievous",
"Un clin d’œil et un sourire en coin.": "A wink and a crooked smile.",
"Étonnée": "Amazed",
"De grands yeux ronds et une petite bouche.": "Big round eyes and a little mouth.",
"Couleur des yeux": "Eye colour",
"Des yeux de la couleur de ton choix.": "Eyes in the colour of your choice.",
"Taille des yeux": "Eye size",
"Petits, normaux ou grands.": "Small, normal or large.",
"Un halo qui flotte au-dessus de sa tête.": "A halo floating above its head.",
"Une tige fine et une petite lanterne.": "A thin stalk and a little lantern.",
"De petites lunettes rondes.": "Little round glasses.",
"Couronne d’étoiles": "Crown of stars",
"Trois étoiles qui flottent.": "Three floating stars.",
"Chapeau de magicien": "Wizard’s hat",
"Pointu et étoilé.": "Pointy and starry.",
"Pour l’accessoire que tu portes.": "For the accessory you’re wearing.",
"Écharpe": "Scarf",
"Une écharpe douce nouée sous le visage.": "A soft scarf tied under its face.",
"Nœud papillon": "Bow tie",
"Un petit nœud bien mis.": "A neat little bow.",
"Cape": "Cape",
"Une cape de lumière qui flotte derrière elle.": "A cape of light floating behind it.",
"Petites ailes": "Little wings",
"Des ailes de lumière qui battent.": "Fluttering wings of light.",
"Petits bras": "Little arms",
"Pour faire coucou.": "For waving hello.",
"Petits pieds": "Little feet",
"Deux petits pieds qui pendent.": "Two little dangling feet.",
"Plus petite ou plus grande.": "Smaller or bigger.",
"Elle sème de petites étincelles.": "It scatters little sparks.",
"Ciel Aube": "Dawn sky",
"Un ciel rose et violet, comme au petit matin.": "A pink and violet sky, like early morning.",
"Ciel Océan": "Ocean sky",
"Un ciel bleu profond, comme sous la mer.": "A deep blue sky, like under the sea.",
"Ciel Papier": "Paper sky",
"Un ciel clair, comme une page de carnet.": "A pale sky, like a notebook page.",
"Les nébuleuses deviennent des nuages épais.": "The nebulae become thick clouds.",
"Tes étoiles se mettent à scintiller.": "Your stars begin to twinkle.",
"Le ciel tourne lentement sur lui-même.": "The sky slowly turns on itself.",
"Réglages de lumière": "Light settings",
"Lueur, profondeur de champ et effet cinéma.": "Glow, depth of field and cinema effect.",
"Couleurs des humeurs": "Mood colours",
"Choisis la couleur de chaque humeur.": "Choose the colour of each mood.",
"La Lune": "The Moon",
"La vraie lune du jour, avec sa phase.": "Today’s real moon, with its phase.",
"Planète à anneaux": "Ringed planet",
"Une planète dorée et ses anneaux, au loin.": "A golden planet and its rings, far away.",
"Planète océan": "Ocean planet",
"Une planète bleue aux nuages blancs.": "A blue planet with white clouds.",
"Géante rouge": "Red giant",
"Une énorme planète rousse, à l’horizon.": "A huge russet planet on the horizon.",
"Voie lactée": "Milky Way",
"Une grande bande de lumière au loin.": "A great band of light in the distance.",
"Poussière d’étoiles": "Stardust",
"Un voile de poussière qui traverse le ciel.": "A veil of dust drifting across the sky.",
"Étoiles filantes": "Shooting stars",
"Elles traversent ton ciel de temps en temps.": "They cross your sky now and then.",
"Satellites": "Satellites",
"Un petit point qui clignote et passe.": "A little blinking dot passing by.",
"Lucioles": "Fireflies",
"De petites étincelles qui tournent autour de tes étoiles.": "Little sparks circling your stars.",
"Comètes": "Comets",
"Une longue queue de lumière, de temps en temps.": "A long tail of light, now and then.",
"Dessins d’étoiles": "Star drawings",
"Parfois, les étoiles dessinent une forme.": "Sometimes the stars draw a shape.",
"Aurores boréales": "Northern lights",
"Un rideau de lumière ondule dans le ciel.": "A curtain of light ripples across the sky.",
"Baleine d’étoiles": "Star whale",
"Une baleine de lumière nage au loin.": "A whale of light swims in the distance.",
// v40 : planètes
"Planètes": "Planets",
"Planète solide": "Rocky planet",
"Des océans et des continents, à nommer et à personnaliser.": "Oceans and continents, to name and customise.",
"Planète gazeuse": "Gas planet",
"Des bandes de couleurs qui tournent doucement.": "Bands of colour that slowly turn.",
"Nuages vaporeux": "Wispy clouds",
"De fins voiles de nuages autour de tes planètes.": "Thin veils of cloud around your planets.",
"Cerisiers": "Cherry trees",
"Des cerisiers en fleurs qui luisent.": "Glowing cherry trees in bloom.",
"Sapins": "Fir trees",
"Des sapins tout ronds.": "Little round fir trees.",
"Maisonnettes": "Little houses",
"Des petites maisons rondes, la fenêtre allumée.": "Small round houses with a lit window.",
"Anneaux": "Rings",
"Fins, larges ou penchés, autour de tes planètes.": "Thin, wide or tilted, around your planets.",
"Double anneau": "Double ring",
"Un second anneau, plus loin.": "A second ring, further out.",
"Couleurs libres": "Free colours",
"Choisis toi-même la couleur des océans, des terres, des bandes.": "Pick the colour of the oceans, lands and bands yourself.",
"Printemps": "Spring",
"Pêche": "Peach",
"Banquise": "Ice",
"Désert": "Desert",
"Lavande": "Lavender",
"Menthe": "Mint",
"Or": "Gold",
"Braise": "Ember",
"Lilas": "Lilac",
"Planète {n}": "Planet {n}",
"Nom de la planète": "Planet name",
"Mes planètes": "My planets",
"Nom": "Name",
"Type": "Type",
"Solide": "Rocky",
"Gazeuse": "Gas",
"Bande 1": "Band 1",
"Bande 2": "Band 2",
"Terre": "Land",
"Sable": "Sand",
"Éléments": "Features",
"Nuages": "Clouds",
"Fin": "Thin",
"Large": "Wide",
"Penché": "Tilted",
"Dans ton ciel": "In your sky",
"Visible": "Visible",
"Rangée": "Put away",
"Tu n’as pas encore de planète. Il y en a dans la boutique.": "You don’t have a planet yet. There are some in the shop.",
"Une nouvelle planète": "A new planet",
"Ton ciel a déjà six planètes.": "Your sky already has six planets.",
"Nouvelle planète : {nom}": "New planet: {nom}",
"Ta planète maison grandit.": "Your home planet is growing.",
"Cadeau : ✦{n} de poussière d’étoiles pour essayer les planètes.": "A gift: ✦{n} stardust to try the planets.",
"Effacer un chiffre": "Delete a digit",
"Code oublié ?": "Forgot your code?",
"Ton code": "Your code",
"Ce n’est pas le bon code.": "That’s not the right code.",
"Choisis un code à 4 chiffres": "Choose a 4-digit code",
"Il sera demandé à chaque ouverture.": "It will be asked every time you open the app.",
"Tape-le encore une fois": "Type it once more",
"Les deux codes sont différents. On recommence.": "The two codes don’t match. Let’s start again.",
"Verrou": "Lock",
"Changer le code": "Change the code",
"Retirer le verrou": "Remove the lock",
"Le verrou est retiré.": "The lock is removed.",
"Ajouter un code": "Add a code",
"Le code sera demandé à chaque ouverture.": "The code will be asked every time you open the app.",
"Il y a un an, ce jour-là": "One year ago, on this day",
"Il y a {n} ans, ce jour-là": "{n} years ago, on this day",
"Il y a un mois, ce jour-là": "One month ago, on this day",
"Il y a une semaine, ce jour-là": "One week ago, on this day",
"On y retourne ?": "Shall we go back?",
"Ça fait {n} jours… qu’est-ce qui s’est passé ?": "It’s been {n} days… what happened?",
"Hier était lourd. Et aujourd’hui ?": "Yesterday was heavy. And today?",
"Qu’est-ce qui t’a fait du bien aujourd’hui ?": "What did you good today?",
"Hier brillait. Ça continue ?": "Yesterday was bright. Still shining?",
"Qu’est-ce qui t’a donné de l’élan aujourd’hui ?": "What gave you a lift today?",
"Avant de dormir : une chose à garder de ta journée ?": "Before sleep: one thing to keep from today?",
"Qu’est-ce qui tourne dans ta tête ce soir ?": "What’s on your mind tonight?",
"Quel moment de ta journée mérite une étoile ?": "Which moment of your day deserves a star?",
"Qu’est-ce qui t’a surpris aujourd’hui ?": "What surprised you today?",
"Une personne à qui tu as pensé aujourd’hui ?": "Someone you thought of today?",
"Qu’as-tu appris aujourd’hui ?": "What did you learn today?",
"Renommer ta constellation": "Rename your constellation",
"Ta semaine forme une constellation": "Your week forms a constellation",
"{n} étoiles, du {a} au {b}. Quel nom lui donnes-tu ?": "{n} stars, from {a} to {b}. What will you call it?",
"ex. La semaine des retrouvailles": "e.g. The week of reunions",
"Nommer": "Name it",
"« {nom} » brille dans ton ciel. +✦{n}": "“{nom}” shines in your sky. +✦{n}",
"Constellation renommée.": "Constellation renamed.",
"Ta semaine forme une constellation. Tu lui donnes un nom ?": "Your week forms a constellation. Will you name it?",
"Ta semaine forme une constellation ! Tu lui donnes un nom ?": "Your week forms a constellation! Will you name it?",
"Renommer la constellation de la semaine": "Rename this week’s constellation",
"Nommer la constellation de la semaine": "Name this week’s constellation",
"constellation semaine figure nom": "constellation week figure name",
"C’est {vrai} : {n} étoiles allumées, du {a} au {b}. Quel nom lui donnes-tu ?": "It’s {vrai}: {n} stars lit, from {a} to {b}. What will you call it?",
"Sport": "Sport",
"Amis": "Friends",
"Famille": "Family",
"Amour": "Love",
"Travail": "Work",
"Études": "Studies",
"Nature": "Nature",
"Création": "Creating",
"Lecture": "Reading",
"Musique": "Music",
"Bien dormi": "Slept well",
"Écrans": "Screens",
"Son": "Sound",
"Ambiance": "Ambience",
"Sons des étoiles": "Star sounds",
"Ce qui va avec tes bons jours": "What goes with your good days",
"Encore quelques jours avec des activités cochées, et le lien avec ton humeur apparaîtra ici.": "A few more days with activities ticked, and the link with your mood will show here.",
"Coche tes activités en écrivant (sport, amis, travail…) : au bout de quelques jours, tu verras ce qui va avec tes bons jours.": "Tick your activities when you write (sport, friends, work…): after a few days, you’ll see what goes with your good days.",
"Les jours avec « {a} », ton ciel est plus dégagé que d’habitude.": "On days with “{a}”, your sky is clearer than usual.",
"Pas encore de lien net : continue de cocher tes activités.": "No clear link yet: keep ticking your activities.",
"Activités du jour": "Today’s activities",
"Je t’ai rapporté : {o} ! Il est rangé dans « {ou} ».": "I brought you back: {o}! It’s stored in “{ou}”.",
"Voyage {n} · {titre}": "Journey {n} · {titre}",
"Voyage terminé : {o} rapporté. Le prochain commence au prochain jour écrit.": "Journey complete: {o} brought back. The next one starts on your next written day.",
"Étape {n} sur 7 · encore {r} jour(s) écrit(s), puis : {o}.": "Step {n} of 7 · {r} more written day(s), then: {o}.",
"Je t’attends ici. Écris un jour de plus pour continuer.": "I’m waiting here. Write one more day to go on.",
"Revoir l’étape": "Replay this step",
"Simuler un jour écrit (essai)": "Simulate a written day (test)",
"Je rêve de partir en voyage… Touche-moi pour voir mon carnet.": "I dream of going on a journey… Tap me to see my travel log.",
"Carnet de voyage": "Travel log",
"voyage aventure lueur etape": "journey adventure glow step",
"Ta semaine est devenue {vrai} ! Tu lui donnes un nom ?": "Your week became {vrai}! Will you name it?",
"Ta semaine est devenue {vrai} !": "Your week became {vrai}!",
"Oh, regarde ! C’est {vrai} !": "Oh, look! It’s {vrai}!",
"Tadaa ! {vrai}, rien que pour toi.": "Ta-da! {vrai}, just for you.",
"Tu as dessiné {vrai} avec tes journées.": "You drew {vrai} with your days.",
"Regarde ce qu’on a fait : {vrai} !": "Look what we made: {vrai}!",
"{vrai} brille dans ton ciel maintenant.": "{vrai} shines in your sky now.",
"Des marins se guidaient avec {vrai}. Toi, tu l’as écrite.": "Sailors found their way with {vrai}. You wrote it.",
"Une constellation de plus : {vrai} !": "One more constellation: {vrai}!",
"Toutes tes étoiles sont allumées. Bravo !": "All your stars are lit. Well done!",
"Pas un jour de raté. Je suis fière de toi !": "Not a single day missed. I’m so proud of you!",
"Une semaine complète : {vrai} brille de partout !": "A full week: {vrai} shines all over!",
"{vrai} est là, même avec quelques étoiles pâles.": "{vrai} is here, even with a few pale stars.",
"Chaque jour écrit l’a fait briller un peu plus.": "Every day you wrote made it shine a little more.",
"Bravo {p}, c’est {vrai} !": "Well done {p}, it’s {vrai}!",
"{p}, regarde : {vrai} !": "{p}, look: {vrai}!",
"Ma semaine": "My week",
"{titre} · étape {n} sur 7": "{titre} · step {n} of 7",
"Il commence au prochain jour écrit": "It starts on your next written day",
"Bilan de ta dernière semaine": "Your last week's summary",
"Personnaliser, renommer, un souvenir": "Customise, rename, a memory",
"Ambiance, astres, animations": "Mood, stars, animations",
"Rappel, son, verrou, tes données": "Reminder, sound, lock, your data",
"voyage : étape {n} sur 7": "journey: step {n} of 7",
"joystick": "joystick",
"Joystick à l’écran": "On-screen joystick",
"Les gestes suffisent : glisse pour tourner, pince pour zoomer, deux doigts pour te déplacer.": "Gestures are enough: drag to turn, pinch to zoom, two fingers to move.",
"Zone sensible": "Danger zone",
"Demande deux confirmations. Exporte ton journal avant.": "Asks twice. Export your journal first.",
"Chaque jour": "Every day",
"Affichage": "Display",
"Protection": "Privacy",
"Sauvegarde, export, import": "Backup, export, import",
"Code à 4 chiffres": "4-digit code",
"Aucun code": "No code",
"Ta semaine · {vrai}": "Your week · {vrai}",
"Du {a} au {b}": "From {a} to {b}",
"{n} jour écrit sur {m}": "{n} day written out of {m}",
"{n} jours écrits sur {m}": "{n} days written out of {m}",
"{n} mot écrit": "{n} word written",
"{n} mots écrits": "{n} words written",
"Humeur la plus présente : {h}": "Most frequent mood: {h}",
"Lui donner un nom": "Give it a name",
"Semaine suivante": "Next week",
"Simuler la fin de semaine (essai)": "Simulate the end of the week (test)",
"constellation semaine recompense": "constellation week reward",
"Renommer ta dernière constellation": "Rename your latest constellation",
"Nommer ta dernière constellation": "Name your latest constellation",
// v55 : une boutique plus variée
"Crépuscule": "Dusk",
"Boréal": "Boreal",
"Galaxie": "Galaxy",
"Une galaxie spirale qui tourne doucement en elle.": "A spiral galaxy slowly turning inside it.",
"Pierre de lune": "Moonstone",
"Une surface nacrée semée de petits cratères.": "A pearly surface dotted with tiny craters.",
"Petite comète": "Little comet",
"Une comète apprivoisée qui file autour d’elle.": "A tame comet that zips around it.",
"Croissant de lune": "Crescent moon",
"Un croissant de lune qui flotte au-dessus de sa tête.": "A crescent moon floating above its head.",
"Ciel Crépuscule": "Dusk sky",
"Le bas du ciel garde un reste de soleil couchant.": "The bottom of the sky keeps a trace of sunset.",
"Ciel Boréal": "Boreal sky",
"Un ciel du Grand Nord, vert profond.": "A Far North sky, deep green.",
"Ciel Nébuleuse": "Nebula sky",
"Tout ton ciel baigne dans une nébuleuse rose et violette.": "Your whole sky bathes in a pink and violet nebula.",
"Nébuleuses lointaines": "Distant nebulae",
"De grands nuages de couleur, tout au fond du ciel.": "Large colourful clouds, far at the back of the sky.",
"Cristaux": "Crystals",
"Des cristaux de lumière qui poussent sur les terres.": "Crystals of light growing on the land.",
"Une petite lune qui tourne autour de ta planète.": "A little moon circling your planet.",
"Aurores polaires": "Polar auroras",
"Un voile de lumière qui danse au-dessus du pôle.": "A veil of light dancing above the pole.",
"Pluie de météores": "Meteor shower",
"De temps en temps, une averse d’étoiles filantes.": "Every now and then, a shower of shooting stars.",
"Corail": "Coral",
"Autour d’elle": "Around it",
// v56 : jouer avec la lueur
"Pfiou ! Quel voyage.": "Phew! What a trip.",
"Tu m’as lancée loin !": "You threw me so far!",
"Encore ! … Non, en fait.": "Again! … Actually, no.",
"Me revoilà !": "I’m back!",
"Hop !": "Hop!",
"Tadaa !": "Ta-da!",
"Une pirouette !": "A pirouette!",
"Youpi !": "Yippee!",
"Wiii !": "Wheee!",
"Où on va ?": "Where are we going?",
"Hé, doucement !": "Hey, gently!",
"Je vole !": "I’m flying!",
"Hahaha ! Arrête !": "Hahaha! Stop!",
"Hihihi, ça chatouille !": "Hehehe, that tickles!",
"Hahaha !": "Hahaha!",
"Wiiiii !": "Wheeeee!",
"Aaaah !": "Aaaah!",
"Je vooole !": "I’m flyyying!",
"Ici, c’est bien.": "It’s nice here.",
"Je reste là.": "I’ll stay here.",
"Merci pour la balade !": "Thanks for the ride!",
"Bonjour ! Bien dormi ?": "Good morning! Did you sleep well?",
"Le ciel se réveille doucement.": "The sky is slowly waking up.",
"C’est l’heure de manger, non ?": "Isn’t it time to eat?",
"Comment s’est passée ta journée ?": "How was your day?",
"La nuit tombe, les étoiles arrivent.": "Night is falling, the stars are coming out.",
"Il est tard…": "It’s late…",
"Tu ne dors pas ?": "Can’t sleep?",
"Ton étoile d’aujourd’hui brille bien.": "Today’s star is shining bright.",
"Tu me racontes ta journée ?": "Will you tell me about your day?",
"Une étoile pour aujourd’hui ?": "A star for today?",
"Mon anneau brille, non ?": "My halo shines, doesn’t it?",
"Mon antenne capte les étoiles.": "My antenna picks up the stars.",
"Je vois tout, avec ces lunettes.": "I see everything with these glasses.",
"Je suis la reine des étoiles.": "I’m the queen of the stars.",
"Abracadabra !": "Abracadabra!",
"Je suis une petite planète !": "I’m a little planet!",
"Ma lune me tient compagnie.": "My moon keeps me company.",
"Bip bip.": "Beep beep.",
"Ma comète me suit partout.": "My comet follows me everywhere.",
"Tu as vu mon croissant ?": "Have you seen my crescent?",
"Je brille comme une perle.": "I shine like a pearl.",
"Brr, j’ai un peu froid.": "Brr, I’m a little cold.",
"Je pétille !": "I’m sparkling!",
"Ça tourbillonne en moi.": "It’s swirling inside me.",
"J’ai des aurores plein le cœur.": "My heart is full of auroras.",
"Il fait nuit, à l’intérieur de moi.": "It’s night inside me.",
"Je chauffe un peu, attention.": "I’m a bit hot, careful.",
"J’ai toute une galaxie dans le ventre.": "I have a whole galaxy in my tummy.",
"Je suis faite de pierre de lune.": "I’m made of moonstone.",
"Miaou !": "Meow!",
"Bouh ! … Je t’ai fait peur ?": "Boo! … Did I scare you?",
"Je suis une vraie étoile.": "I’m a real star.",
"Je file comme une comète !": "I zoom like a comet!",
"Oui, c’est moi, {nom} !": "Yes, it’s me, {nom}!",
"{n} caresses ! Je les compte, tu sais.": "{n} pats! I’m counting, you know.",
"Coucou !": "Hi there!",
"Tu m’as trouvée !": "You found me!",
"Je suis contente de te voir.": "I’m happy to see you.",
"On fait un tour ?": "Shall we go for a ride?",
"Je t’aime bien.": "I like you.",
"Tu peux me prendre et me promener, tu sais.": "You can pick me up and carry me around, you know.",
"Touche-moi deux fois, pour voir.": "Tap me twice, just to see.",
"Frotte-moi vite, pour voir…": "Rub me fast, just to see…",
// v57 : filantes, endroit montré, bonjour et bonne nuit, cache-cache
"Bonjour ! J’ai bien dormi.": "Good morning! I slept well.",
"Hm ? Déjà le matin ?": "Hm? Morning already?",
"Zzz…": "Zzz…",
"Encore cinq minutes…": "Five more minutes…",
"Mmh… bonne nuit…": "Mmm… good night…",
"Bonne nuit… à demain.": "Good night… see you tomorrow.",
"Dors bien, moi aussi…": "Sleep well, me too…",
"Bonne nuit, je garde tes étoiles.": "Good night, I’ll watch over your stars.",
"Bonjour ! {n} jours d’affilée, on continue ?": "Good morning! {n} days in a row, shall we keep going?",
"Bonjour ! Hier, tu as écrit. On recommence ?": "Good morning! You wrote yesterday. Again today?",
"Bonjour ! Une nouvelle journée commence.": "Good morning! A new day begins.",
"Zzz… pas maintenant…": "Zzz… not now…",
"Attrapée !": "Caught it!",
"Je l’ai !": "Got it!",
"Elle est toute chaude !": "It’s still warm!",
"Un vœu pour toi !": "A wish for you!",
"Zzz… demain…": "Zzz… tomorrow…",
"Mmh… plus tard…": "Mmm… later…",
"Oh, cette étoile-là ?": "Oh, that star?",
"Je vais voir !": "I’ll go and see!",
"J’arrive !": "Coming!",
"Là-bas ?": "Over there?",
"On va voir !": "Let’s go see!",
"Rien ici… juste du ciel.": "Nothing here… just sky.",
"C’est joli, par ici.": "It’s pretty over here.",
"Un jour, il y aura une étoile ici.": "One day, there’ll be a star here.",
"Je reste un peu là.": "I’ll stay here a while.",
"On joue à cache-cache ? Touche ici.": "Hide and seek? Tap here.",
"Compte jusqu’à trois… je me cache !": "Count to three… I’m hiding!",
"Trouvée !": "Found me!",
"Zut, tu m’as eue !": "Oh no, you got me!",
"Bravo, j’étais là !": "Well done, I was here!",
"Coucou ! J’étais là, tu ne m’as pas trouvée.": "Peekaboo! I was here, you didn’t find me.",
"Touche-la, je l’attrape !": "Tap it, I’ll catch it!",
"Touche deux fois le ciel, j’irai voir.": "Tap the sky twice and I’ll go look.",
"Un long câlin, et je vais au lit.": "A long hug, and off to bed I go.",
"Touche une étoile filante, je l’attrape !": "Tap a shooting star and I’ll catch it!",
"Étoile filante attrapée": "Shooting star caught",
"Touche les étoiles pour la trouver": "Tap the stars to find her",
"Chaud !": "Hot!",
"Tiède…": "Warm…",
"Froid…": "Cold…",
"Il me faut plus d’étoiles autour pour me cacher…": "I need more stars around to hide…",
"Une filante dorée !": "A golden shooting star!",
"Elle te l’a rapportée": "She brought it back for you",
"Elle a l’air bonne, ton étoile…": "Your star looks tasty…",
"Juste une bouchée…": "Just one bite…",
"Un petit tour de ton étoile !": "A little lap around your star!",
"Je fais le tour !": "Going round!",
"Je fais la planche…": "Floating on my back…",
"Je me laisse flotter.": "Just drifting.",
"Regarde, je jongle !": "Look, I'm juggling!",
"Hop, hop, hop !": "Hop, hop, hop!",
"Je la fais briller pour toi.": "I'll make it shine for you.",
"Un peu de poussière, là…": "A bit of dust, right there…",
"Une petite sieste…": "A little nap…",
"Je me pose un peu.": "Time for a rest.",
"Ta-da !": "Ta-da!",
"Et voilà !": "There you go!",
"Ah, ça fait du bien.": "Ah, that felt good.",
"Petite sieste… finie !": "Nap… over!",
"Je fais un vœu…": "Making a wish…",
"Un vœu pour toi.": "A wish for you.",
"Chut, je fais un vœu.": "Shh, I'm making a wish.",
"Ooooh…": "Ooooh…",
"Waouh…": "Wow…",
"Tu as vu ?": "Did you see?",
"Elle file !": "There it goes!",
"Regarde-la filer.": "Watch it fly.",
"Attends-moi !": "Wait for me!",
"Je l’attrape !": "I'll catch it!",
"Elle est à moi !": "It's mine!",
"Je l’ai eue toute seule !": "I caught it all by myself!",
"Attrapée ! Pour toi.": "Caught it! For you.",
"Raté… elle va trop vite.": "Missed… it's too fast.",
"Zut, envolée !": "Drat, it's gone!",
"Pfff, la prochaine fois.": "Pfff, next time.",
"Miam !": "Yum!",
"Crounch !": "Crunch!",
"*croque*": "*crunch*",
"Pouah ! Ça pique.": "Yuck! It stings.",
"Trop chaud !": "Too hot!",
"Beurk, ça brille trop !": "Ew, way too bright!",
"Bon… je te la rends.": "Fine… you can have it back.",
"Toute propre !": "All clean!",
"Elle brille, hein ?": "Shiny, right?",
"Voilà, comme neuve.": "There, good as new.",
"Atchoum !": "Achoo!",
"A… a…": "Ah… ah…",
"Ah… ah…": "Ah… ah…",
"Oh ! Je faisais la sieste.": "Oh! I was napping.",
"Hm ? J’étais bien, là…": "Hm? I was comfy…",
"Éclat de comète": "Comet shard",
"Grain de lune": "Moon grain",
"Caillou de Mars": "Mars pebble",
"Plume d’aurore": "Aurora feather",
"Goutte de nébuleuse": "Nebula drop",
"Petite météorite": "Tiny meteorite",
"Glace de Saturne": "Saturn ice",
"Anneau de poche": "Pocket ring",
"Étoile tombée": "Fallen star",
"Flocon cosmique": "Cosmic snowflake",
"Perle d’aurore": "Aurora pearl",
"Larme d’étoile": "Star tear",
"Coquille de galaxie": "Galaxy shell",
"Fiole de poussière": "Vial of stardust",
"Quartz lunaire": "Moon quartz",
"Bille de soleil": "Sun marble",
"Fragment d’astéroïde": "Asteroid fragment",
"Lentille de télescope": "Telescope lens",
"Graine de nébuleuse": "Nebula seed",
"Étoile endormie": "Sleeping star",
"Fil de comète": "Comet thread",
"Lune de poche": "Pocket moon",
"Cristal d’aurore": "Aurora crystal",
"Sablier d’étoiles": "Star hourglass",
"Arc-en-ciel de lune": "Moonbow",
"Éclat de supernova": "Supernova shard",
"Pierre de lune bleue": "Blue moonstone",
"Pépite d’or stellaire": "Stellar gold nugget",
"Étoile filante en bocal": "Shooting star in a jar",
"Cœur d’étoile": "Star heart",
"Tombé de la queue d’une comète qui passait par là.": "Fell from the tail of a passing comet.",
"Un peu de poussière grise, ramassée sur la face cachée.": "A bit of grey dust, picked up on the far side.",
"Rouge comme sa planète. Il sent un peu la rouille.": "Red like its planet. It smells a little of rust.",
"Elle a ondulé toute une nuit au-dessus du pôle.": "It rippled all night above the pole.",
"Une étoile est peut-être en train de naître dedans.": "A star may be being born inside.",
"Encore tiède. Elle a traversé le ciel pour arriver jusqu’ici.": "Still warm. It crossed the sky to get here.",
"Un glaçon tombé des anneaux. Il ne fond pas.": "An ice cube fallen from the rings. It never melts.",
"Un anneau de planète, juste à ta taille.": "A planet ring, just your size.",
"Elle s’est décrochée du ciel. Elle brille encore un peu.": "It came loose from the sky. It still glows a little.",
"Il ne fond jamais : il fait bien trop froid là-haut.": "It never melts: it’s far too cold up there.",
"Une perle verte qui ondule quand on la regarde.": "A green pearl that ripples when you look at it.",
"Une étoile a pleuré de joie. La voici.": "A star cried with joy. Here it is.",
"Approche-la de ton oreille : on entend le ciel tourner.": "Hold it to your ear: you can hear the sky turning.",
"Une pincée de poussière d’étoiles, bien bouchée.": "A pinch of stardust, tightly corked.",
"Il pousse en silence dans les cratères.": "It grows quietly inside craters.",
"Un tout petit morceau de lever de soleil.": "A tiny piece of sunrise.",
"Il vient de la ceinture, entre Mars et Jupiter.": "It comes from the belt, between Mars and Jupiter.",
"Perdue par un astronome distrait.": "Lost by an absent-minded astronomer.",
"Plante-la dans le ciel. Qui sait ce qui poussera ?": "Plant it in the sky. Who knows what will grow?",
"Elle dort. Ne la réveille pas.": "It’s asleep. Don’t wake it.",
"Un fil de lumière, enroulé pour le voyage.": "A thread of light, coiled up for the journey.",
"Une lune toute ronde. Elle a ses phases, elle aussi.": "A perfectly round moon. It has phases too.",
"Vert d’un côté, violet de l’autre.": "Green on one side, violet on the other.",
"Le temps y coule en poussière bleue.": "Time flows through it as blue dust.",
"Un arc-en-ciel de nuit, tout pâle.": "A pale night-time rainbow.",
"Le reste d’une étoile qui a explosé, il y a très longtemps.": "What’s left of a star that exploded long ago.",
"On n’en trouve qu’une fois tous les trente-six du mois.": "You only find one once in a blue moon.",
"Fabriquée au cœur d’une étoile géante.": "Forged in the heart of a giant star.",
"Elle tourne en rond, toute contente.": "It goes round and round, very happy.",
"Le cœur d’une étoile, tout chaud. Le plus rare de tous.": "The heart of a star, still warm. The rarest of all.",
"Ses trouvailles": "Her finds",
"{n} sur {m} · elle en rapporte une par jour où tu écris": "{n} of {m} · she brings one back each day you write",
"Rien pour l’instant": "Nothing yet",
"Écris aujourd’hui : elle partira chercher quelque chose pour toi.": "Write today: she’ll go and look for something for you.",
"très rare": "very rare",
"rare": "rare",
"Trouvée le {d}": "Found on {d}",
"On se découvre": "Getting to know each other",
"Copains d’étoile": "Star buddies",
"Complices": "Partners in crime",
"Inséparables": "Inseparable",
"Étoiles jumelles": "Twin stars",
"Constellation à deux": "A constellation for two",
"Elle te demande ton prénom et l’utilise.": "She asks your first name and uses it.",
"Des bisous et des mots tendres quand tu la touches.": "Kisses and sweet words when you touch her.",
"Elle dessine des cœurs d’étoiles dans le ciel.": "She draws hearts of stars in the sky.",
"Elle t’accueille à chaque visite.": "She welcomes you every visit.",
"Une couronne d’étoiles tourne autour d’elle.": "A crown of stars circles around her.",
"Un cœur pour toi, {p}.": "A heart for you, {p}.",
"Un cœur pour toi.": "A heart for you.",
"Regarde bien…": "Watch closely…",
"Pour toi.": "For you.",
"Tadaa, un cœur !": "Ta-da, a heart!",
"Attends-moi, je reviens !": "Wait for me, I’ll be back!",
"Je vais te chercher quelque chose…": "I’ll go find you something…",
"Je pars en balade, je reviens vite.": "Off for a wander, back soon.",
"Regarde ce que j’ai trouvé : {o} !": "Look what I found: {o}!",
"Bisou !": "Kiss!",
"♥ Smack !": "♥ Smack!",
"Je t’aime fort, {p}.": "I love you lots, {p}.",
"Je t’aime fort.": "I love you lots.",
"Tu es mon étoile préférée, {p}.": "You’re my favourite star, {p}.",
"Tu es mon étoile préférée.": "You’re my favourite star.",
"Coucou {p} !": "Hi {p}!",
"{p} ! Je pensais à toi.": "{p}! I was thinking of you.",
"Tu sais quoi, {p} ? Je suis bien avec toi.": "You know what, {p}? I’m happy with you.",
"Je reste là pendant l’orage.": "I’ll stay here through the storm.",
"Je reste près de toi, d’accord ?": "I’ll stay close to you, okay?",
"Nouvelle trouvaille : {o}": "New find: {o}",
"Tu parles beaucoup de {n} en ce moment.": "You talk about {n} a lot lately.",
"{n} revient souvent dans tes étoiles cette semaine.": "{n} keeps coming back in your stars this week.",
"{n}, {j} jours cette semaine. C’est quelqu’un d’important ?": "{n}, {j} days this week. Someone important?",
"{n} revient souvent cette semaine.": "{n} keeps coming back this week.",
"Tu es allé·e souvent à {n} ces jours-ci.": "You’ve been to {n} a lot lately.",
"{n}, {j} fois cette semaine. Ton endroit préféré ?": "{n}, {j} times this week. Your favourite place?",
"Tu parlais de {n} ici. Ça m’a fait sourire.": "You wrote about {n} here. It made me smile.",
"{n} était là ce jour-là.": "{n} was there that day.",
"J’aime bien quand tu parles de {n}.": "I like it when you write about {n}.",
"{n}… tu y retournes bientôt ?": "{n}… going back soon?",
"Ah, {n}. Je m’en souviens.": "Ah, {n}. I remember.",
"Il y avait de la joie dans cette étoile.": "There was joy in this star.",
"Cette note sent le bonheur.": "This note smells like happiness.",
"Ce jour-là pesait un peu. Regarde le chemin depuis.": "That day was heavy. Look how far you’ve come.",
"Tu as traversé ça. Je suis fière de toi.": "You got through that. I’m proud of you.",
"Il y avait du ciel dans ce que tu as écrit.": "There was sky in what you wrote.",
"Quelle belle journée c’était !": "What a lovely day it was!",
"Cette étoile brille plus que les autres, non ?": "This star shines brighter than the others, right?",
"Une journée douce. J’aime bien cette étoile.": "A gentle day. I like this star.",
"Elle est paisible, celle-là.": "This one is peaceful.",
"Tu avais plein d’énergie ce jour-là !": "You had so much energy that day!",
"Celle-ci pétille encore.": "This one still sparkles.",
"Une étoile un peu bleue. Elle compte aussi.": "A slightly blue star. It counts too.",
"Même les jours gris font de belles étoiles.": "Even grey days make beautiful stars.",
"Un jour d’orage… et pourtant, elle brille.": "A stormy day… and still, it shines.",
"Tu as tenu bon ce jour-là.": "You held on that day.",
"Je tourne autour de tes souvenirs.": "I’m circling your memories.",
"Tu avais beaucoup à dire ce jour-là.": "You had a lot to say that day.",
"Ah, {n} !": "Oh, {n}!",
"Coucou {n} !": "Hi {n}!",
"Je me souviendrai de {n}.": "I’ll remember {n}.",
"{n}, je note.": "{n}, noted.",
"J’aimerais voir {n}.": "I’d love to see {n}.",
"Ah, à {n} ?": "Oh, at {n}?",
"Notre amitié grandit : {nom} !": "Our friendship is growing: {nom}!",
"Comment tu t’appelles ?": "What’s your name?",
"{nom} aimerait t’appeler par ton prénom.": "{nom} would like to call you by your first name.",
"Ton prénom": "Your first name",
"Enchantée, {p} !": "Nice to meet you, {p}!",
"Votre amitié · {nom}": "Your friendship · {nom}",
"Encore {n} points avant le palier suivant. Un jour écrit en donne 10, jouer avec elle jusqu’à 3 par jour.": "{n} more points to the next level. A day written gives 10, playing with her up to 3 a day.",
"Le plus beau palier. Elle ne te quitte plus.": "The finest level. She never leaves your side.",
"à {n} points": "at {n} points",
"Changer ton prénom": "Change your first name",
"Lui dire ton prénom": "Tell her your first name",
"{n} sur {m}": "{n} of {m}",
"Votre amitié": "Your friendship",
"Personnaliser, trouvailles, amitié": "Customise, finds, friendship",
"Te voilà, {p} !": "There you are, {p}!",
"Te voilà !": "There you are!",
"Le plus souvent : {p}, {n} jour": "Most often: {p}, {n} day",
"Le plus souvent : {p}, {n} jours": "Most often: {p}, {n} days",
"Le lieu du mois : {p}, {n} jour": "Place of the month: {p}, {n} day",
"Le lieu du mois : {p}, {n} jours": "Place of the month: {p}, {n} days",
"Ta plus longue note : le {d}, {n} mot": "Your longest entry: {d}, {n} word",
"Ta plus longue note : le {d}, {n} mots": "Your longest entry: {d}, {n} words",
"{n} constellation née : {l}": "{n} constellation born: {l}",
"{n} constellations nées : {l}": "{n} constellations born: {l}",
"Relire ce mois": "Reread this month",
"Ton mois · {m}": "Your month · {m}",
"Un mois de plus dans ton ciel.": "One more month in your sky.",
"Un mois de plus dans ton ciel !": "One more month in your sky!",
"Quel mois ! Je suis fière de toi.": "What a month! I’m proud of you.",
"Chercher dans mon journal": "Search my journal",
"Un mot, un @prénom, un #lieu": "A word, a @name, a #place",
"Un mot, un @prénom ou un #lieu.": "A word, a @name or a #place.",
"Pas ce mot exact. Des notes qui s’en approchent :": "Not this exact word. Entries that come close:",
"Rien trouvé dans ton journal.": "Nothing found in your journal.",
"Chercher « {q} » dans mon journal": "Search “{q}” in my journal",
"Ce qui te fait du bien": "What does you good",
"Encore quelques jours écrits, et les liens entre ce que tu vis et ton humeur apparaîtront ici.": "A few more written days, and the links between what you live and your mood will show here.",
"Pas encore de lien net. Coche tes activités et écris @prénom ou #lieu : les liens apparaîtront peu à peu.": "No clear link yet. Tick your activities and write @name or #place: links will show bit by bit.",
"Les jours avec « {a} »": "On days with “{a}”",
"Les jours avec {p}": "On days with {p}",
"Les jours où {p} apparaît": "On days when {p} appears",
"{qui}, tu es plus souvent en joie ou plein d’élan ({b} sur {n}).": "{qui}, you’re more often joyful or full of momentum ({b} of {n}).",
"{qui}, ton ciel est plus souvent gris ({b} sur {n}).": "{qui}, your sky is more often grey ({b} of {n}).",
"J’ai remarqué un truc : {qui}, tu es plus souvent en joie.": "I noticed something: {qui}, you’re more often joyful.",
"Tes humeurs, ce qui te fait du bien, le mois": "Your moods, what does you good, the month",
"MA SEMAINE": "MY WEEK",
"Pas encore de constellation née. Elle naît à la fin de la semaine.": "No constellation born yet. It’s born at the end of the week.",
"Aucun texte de ton journal n’apparaît sur l’image.": "None of your journal’s text appears on the image.",
"Envoyer": "Send",
"Image enregistrée dans tes téléchargements.": "Image saved to your downloads.",
"Envoyer l’image": "Send the image",
"Envoyer ma constellation": "Send my constellation",
"Une image de ta semaine, sans aucun texte": "An image of your week, with no text",
"Mon livre du mois": "My book of the month",
"Ton mois mis en page, à garder en PDF": "Your month laid out, to keep as a PDF",
"Mon journal": "My journal",
"{n} mot": "{n} word",
"{n} mots": "{n} words",
"Aucun jour écrit ce mois-ci.": "No day written this month.",
"Puis choisis « Enregistrer au format PDF ».": "Then choose “Save as PDF”.",
"Enregistrer en PDF": "Save as PDF",
"Un coup de pouce ?": "Need a nudge?",
"Un début de page, pour ne pas partir de rien.": "A start of a page, so you don’t begin from nothing.",
// v78 : le menu en 5 espaces
"Relire, chercher, personnes et lieux, livre du mois": "Reread, search, people and places, book of the month",
"Ma lueur et mon ciel": "My glow and my sky",
"Personnaliser, trouvailles, amitié, ambiance": "Customise, finds, friendship, mood",
"Ta première constellation naîtra à la fin de la semaine.": "Your first constellation will be born at the end of the week.",
"{n} constellation née": "{n} constellation born",
"{n} constellations nées": "{n} constellations born",
"(photo seulement)": "(photo only)",
"Relire": "Reread",
"Rien à relire pour l’instant.": "Nothing to reread yet.",
"Personnes et lieux": "People and places",
"Livre du mois": "Book of the month",
"Derniers jours": "Latest days",
"Voir dans le ciel": "See in the sky",
"Chercher un mot, un @prénom, un #lieu": "Search a word, a @name, a #place",
// v79 : essayer avant d'acheter
"À l’essai": "Trying on",
"Arrêter l’essai": "Stop trying",
"Il te manque ✦{n}": "You need ✦{n} more",
"Acheter ✦{n}": "Buy ✦{n}",
"À l’essai · un exemple": "Trying on · an example",
// v82 : la voix
"Voix": "Voice",
"Ma voix": "My voice",
"Je t’écoute…": "I’m listening…",
"Terminer": "Done",
"Écouter": "Listen",
"Pause": "Pause",
"Ton navigateur ne sait pas enregistrer le son.": "Your browser can’t record sound.",
"Le micro n’est pas autorisé. Autorise-le dans les réglages du navigateur.": "The microphone isn’t allowed. Allow it in your browser settings.",
"Ta voix est prête. Elle sera gardée avec ton entrée.": "Your voice is ready. It will be kept with your entry.",
// v83 : transmettre sa galaxie
"Transmettre": "Pass on",
"Transmettre ma galaxie": "Pass on my galaxy",
"Un fichier protégé par un mot de passe, à lire en souvenir": "A password-protected file, to read as a keepsake",
"La galaxie de {nom}": "{nom}’s galaxy",
"quelqu’un": "someone",
"Ouvrir une galaxie reçue": "Open a galaxy you received",
"Le fichier .constellation qu’on t’a envoyé": "The .constellation file someone sent you",
"Un mot de passe": "A password",
"Mot de passe": "Password",
"Le même, encore une fois": "The same one, again",
"Confirmer le mot de passe": "Confirm the password",
"Choisis un mot de passe d’au moins 4 caractères.": "Choose a password of at least 4 characters.",
"Les deux mots de passe ne sont pas pareils.": "The two passwords don’t match.",
"Je prépare ta galaxie…": "Preparing your galaxy…",
"Ma galaxie": "My galaxy",
"Envoyée. Donne-lui le mot de passe à part, de vive voix si tu peux.": "Sent. Give them the password separately, in person if you can.",
"Le fichier est dans tes téléchargements. Envoie-le, puis donne le mot de passe à part.": "The file is in your downloads. Send it, then give the password separately.",
"Je n’ai pas réussi à préparer le fichier.": "I couldn’t prepare the file.",
"Créer le fichier": "Create the file",
"En souvenir, à lire seulement": "As a keepsake, read only",
"Tes jours, tes humeurs et tes constellations dans un fichier que tu envoies à qui tu veux. Il ne s’ouvre qu’avec le mot de passe que tu choisis ici. La personne pourra le lire, jamais écrire dedans.": "Your days, moods and constellations in a file you send to whoever you like. It only opens with the password you choose here. They’ll be able to read it, never write in it.",
"Signé": "Signed",
"Avec les photos et les voix": "With photos and voices",
"Ce fichier n’est pas une galaxie Constellation.": "This file isn’t a Constellation galaxy.",
"Le mot de passe": "The password",
"J’ouvre la galaxie…": "Opening the galaxy…",
"Ce n’est pas le bon mot de passe.": "That’s not the right password.",
"Je n’arrive pas à lire ce fichier.": "I can’t read this file.",
"Il te faut le mot de passe qu’on t’a donné": "You need the password you were given",
"Ouvrir": "Open",
"Cette galaxie n’est plus là.": "This galaxy is gone.",
"Un souvenir à lire : rien ne s’y écrit.": "A keepsake to read: nothing can be written in it.",
"Relire ses jours": "Reread their days",
"Une page par jour, du premier au dernier": "One page per day, first to last",
"Ses constellations": "Their constellations",
"Pas encore de constellation complète.": "No complete constellation yet.",
"Retirer cette galaxie": "Remove this galaxy",
"Elle disparaît de ce téléphone seulement": "It disappears from this phone only",
"Retirer la galaxie de {nom} de ce téléphone ?": "Remove {nom}’s galaxy from this phone?",
"Galaxie retirée.": "Galaxy removed.",
// v84 : parcours guidé pas à pas, guide de l’écriture
"Il y a des objets pour moi, dans <b>Ta lueur</b>, et d’autres pour décorer ton ciel, dans <b>Ton ciel</b>.": "There are items for me, under <b>Your glow</b>, and others to decorate your sky, under <b>Your sky</b>.",
"On regarde les miens d’abord.": "Let’s look at mine first.",
"Et voilà, ta journée deviendrait une étoile.": "And there, your day would become a star.",
"C’était une répétition : cette note d’essai n’a pas été gardée, ton journal n’a pas bougé.": "That was a rehearsal: this practice note wasn’t kept, your journal hasn’t changed.",
"Sa couleur, c’est ton humeur. Chaque semaine prend la forme d’une vraie constellation.": "Its colour is your mood. Each week takes the shape of a real constellation.",
"Revoir le parcours guidé": "Replay the guided tour",
"Au début d’une ligne, ouvre la liste de tous les blocs, comme le + de la barre.": "At the start of a line, opens the list of all blocks, like the + in the bar.",
"Beau titre ! Tape <b>/</b> au début d’une ligne puis <b>Séparateur</b>.": "Nice title! Type <b>/</b> at the start of a line, then <b>Divider</b>.",
"Beau titre ! Touche <b>—</b> pour le séparer du reste de ta note.": "Nice title! Tap <b>—</b> to set it apart from the rest of your note.",
"Bleu : c’est un lieu.": "Blue: that’s a place.",
"Ce que tu écris, tes humeurs, tes photos et ta voix restent sur ce téléphone. Pas de compte, pas de serveur.": "What you write, your moods, your photos and your voice stay on this phone. No account, no server.",
"Chaque jour où tu écris devient une étoile. Tes semaines deviennent des constellations.": "Every day you write becomes a star. Your weeks become constellations.",
"Chaque jour où tu écris, tu gagnes de la poussière.": "Every day you write, you earn stardust.",
"Choisis l’humeur qui colle à ta journée.": "Pick the mood that fits your day.",
"Clavier ouvert, c’est le ✓ de la barre.": "With the keyboard open, it’s the ✓ in the bar.",
"Coche ce que tu as fait aujourd’hui.": "Tick what you did today.",
"Coup de pouce": "A little nudge",
"Cristalliser : ta journée devient une étoile. Tu peux encore la compléter jusqu’à minuit.": "Crystallize: your day becomes a star. You can still add to it until midnight.",
"C’est bon": "Done",
"C’est mon nom": "That’s my name",
"Des titres, du plus grand au plus petit. Retoucher le même revient au texte normal.": "Headings, from largest to smallest. Tapping the same one again goes back to normal text.",
"Doré : c’est une personne.": "Gold: that’s a person.",
"D’accord": "OK",
"Elle donnera sa couleur à ton étoile.": "It will give your star its colour.",
"Elle reste sur ton téléphone, comme le reste.": "It stays on your phone, like everything else.",
"Enchantée, {nom} ! Écrivons ta première journée. Touche <b>+</b>.": "Nice to meet you, {nom}! Let’s write your first day. Tap <b>+</b>.",
"Enregistre ta voix dans la note. Elle reste sur ton téléphone.": "Records your voice in the note. It stays on your phone.",
"Et la <b>Boutique</b> : ta poussière d’étoiles ✦ s’y échange. Touche-la.": "And the <b>Shop</b>: that’s where you trade your stardust ✦. Tap it.",
"Exemple : avec @Léa, au #parc. Le mot change de couleur.": "For example: with @Léa, at the #park. The word changes colour.",
"Guide de l’écriture": "Writing guide",
"Ici, tout reste à toi.": "Here, everything stays yours.",
"Ici, tu vois ton humeur jour après jour, et je te dis ce qui te fait du bien.": "Here you see your mood day after day, and I tell you what does you good.",
"Il y a d’autres outils : petits titres, listes, citation… Tout est expliqué dans Menu › Réglages › Guide de l’écriture.": "There are other tools: smaller headings, lists, quotes… It’s all explained in Menu › Settings › Writing guide.",
"Le lieu devient bleu, avec son album à lui aussi.": "The place turns blue, with its own album too.",
"Le prénom devient doré. Une fois cristallisé, il ouvre l’album de la personne : tous les jours où elle apparaît.": "The name turns gold. Once crystallized, it opens that person’s album: every day they appear in.",
"Le séparateur trace un trait fin entre deux parties.": "The divider draws a thin line between two parts.",
"Par exemple : Premier jour.": "For example: First day.",
"Parfait. Touche <b>Cristalliser</b> pour garder ta journée.": "Perfect. Tap <b>Crystallize</b> to keep your day.",
"Pas besoin d’en écrire beaucoup.": "No need to write much.",
"Personne d’autre ne peut lire ton journal. Pas même nous.": "Nobody else can read your journal. Not even us.",
"Plus tu écris, plus c’est précis.": "The more you write, the more precise it gets.",
"Pour finir, ajoute quelqu’un avec un <b>@</b> devant son prénom, ou un lieu avec un <b>#</b>.": "To finish, add someone with an <b>@</b> before their name, or a place with a <b>#</b>.",
"Pour tout savoir sur l’écriture : Menu › Réglages › Guide de l’écriture.": "Everything about writing: Menu › Settings › Writing guide.",
"Quand tu écris, une barre apparaît au-dessus du clavier. Voici ce que fait chaque outil.": "When you write, a bar appears above the keyboard. Here’s what each tool does.",
"Revenir au texte normal.": "Back to normal text.",
"Reviens demain, on allumera une nouvelle étoile. Touche-moi quand tu veux : j’adore jouer.": "Come back tomorrow, we’ll light a new star. Tap me whenever you like: I love to play.",
"Rien de tout ça": "None of these",
"Sa couleur, c’est ton humeur. Chaque jour où tu écris, j’en allume une nouvelle, et chaque semaine prend la forme d’une vraie constellation.": "Its colour is your mood. Every day you write, I light a new one, and each week takes the shape of a real constellation.",
"Sous le trait, c’est le <b>contenu</b> de ta note. Raconte un peu ta journée.": "Below the line is the <b>content</b> of your note. Tell me a bit about your day.",
"Suivant": "Next",
"Sur une page vide, une idée pour commencer. Si tu bloques, je peux aussi te poser une question.": "On an empty page, an idea to get started. If you’re stuck, I can also ask you a question.",
"Ta semaine, ton journal à relire, ta lueur, les réglages : tout est ici. Commençons par le <b>Suivi</b>.": "Your week, your journal to reread, your glow, the settings: it’s all here. Let’s start with <b>Tracking</b>.",
"Ta voix devient du texte. La dictée passe par le service de ton téléphone.": "Your voice becomes text. Dictation goes through your phone’s service.",
"Tape <b>/</b> puis choisis <b>Titre 1</b> : cette ligne devient le <b>titre</b> de ta note.": "Type <b>/</b> then choose <b>Heading 1</b>: this line becomes the <b>title</b> of your note.",
"Touche <b>H1</b> : cette ligne devient le <b>titre</b> de ta note, écrit en grand.": "Tap <b>H1</b>: this line becomes the <b>title</b> of your note, written large.",
"Touche la page pour écrire.": "Tap the page to write.",
"Touche un objet pour l’<b>essayer</b> sur moi, même s’il est trop cher.": "Tap an item to <b>try it</b> on me, even if it’s too expensive.",
"Tous les outils du journal, expliqués": "Every journal tool, explained",
"Tout le reste est rangé dans le menu. Touche <b>☰</b>.": "Everything else lives in the menu. Tap <b>☰</b>.",
"Tu gagnes aussi de la poussière d’étoiles ✦. Elle s’échange dans la boutique.": "You also earn stardust ✦. You can trade it in the shop.",
"Tu peux aussi garder ta voix : touche <b>Ma voix</b>, dis un mot, puis <b>Terminer</b>.": "You can also keep your voice: tap <b>My voice</b>, say a word, then <b>Finish</b>.",
"Tu peux continuer, ou passer à la suite.": "You can keep going, or move on.",
"Un séparateur, pour passer à un autre moment de la journée.": "A divider, to move to another moment of the day.",
"Une barre d’outils apparaît au-dessus du clavier.": "A toolbar appears above the keyboard.",
"Une citation, pour une phrase qui t’a marqué.": "A quote, for a sentence that stayed with you.",
"Une liste à puces ou numérotée.": "A bulleted or numbered list.",
"Une photo, une vidéo ou un fichier. « Qui ? Où ? » le range dans les albums.": "A photo, a video or a file. “Who? Where?” files it in the albums.",
"lieu": "place",
"prénom": "name",
"Ça me va bien, non ? <b>Acheter</b> le garde, <b>Retirer</b> l’enlève.": "Suits me, doesn’t it? <b>Buy</b> keeps it, <b>Remove</b> takes it off.",
"Ça m’aidera à voir ce qui te fait du bien.": "It’ll help me see what does you good.",
"Écris ton titre : juste le nom de ta journée, en quelques mots.": "Write your title: just a name for your day, in a few words.",
"Écrivons ta première journée. Touche <b>+</b>.": "Let’s write your first day. Tap <b>+</b>.",
"Texte normal": "Normal text",
};

export const EN_HTML = {
"aide-liste": "\n    <li><b>Pinch</b> or <b>scroll</b>: zoom from years down to a single day</li>\n    <li><b>Tap</b> a nebula or a star to dive into it</li>\n    <li><b>+</b> at the bottom: write · <b>◎</b> on the right: back to today</li>\n    <li><b>Drag</b> to rotate · <b>two fingers</b> to move</li>\n    <li><b>⋯</b>: the menu</li>\n  ",
"aide-exemples": "This sky contains <b>example entries</b>, made up to show you what it looks like. None of it is yours: clear them whenever you like, here or later with <b>⋯</b> → <i>Settings</i>.",
  // v85 : le parcours guidé pour qui écrivait déjà
  'Du nouveau dans ton univers !': 'Something new in your universe!',
  'Je te montre, pas à pas, comment écrire ta journée et où trouver tout le reste.': 'Let me show you, step by step, how to write your day and where to find everything else.',
  'On le fait une seule fois, avec ta vraie note du jour.': 'We only do this once, with your real note for today.',
  'Écrivons ta journée d’aujourd’hui. Touche <b>+</b>.': 'Let’s write today. Tap <b>+</b>.',
  'Et voilà ton étoile du jour !': 'And there’s your star of the day!',
  // v86
  'Touche ta page : la barre d’outils revient au-dessus du clavier. Puis touche <b>H1</b> pour en faire le <b>titre</b>.': 'Tap your page: the toolbar comes back above the keyboard. Then tap <b>H1</b> to make it the <b>title</b>.',
  'Beau titre ! Touche ta page pour faire revenir la barre d’outils, puis <b>—</b> pour le séparer du reste.': 'Nice title! Tap your page to bring the toolbar back, then <b>—</b> to separate it from the rest.',
};
