// v71 : la légende de la semaine (Matthieu). Quand la constellation naît, deux phrases sur son histoire :
// la vraie légende pour les constellations officielles, et pour les chinoises anciennes, ce qu'elles représentaient au ciel de l'Empire.
// Clé : le nom français de ciel-reel.js (et des anciennes figures de figures.js, qui portent les mêmes noms).
import { EN } from './langue.js';

const L = {
  // ── constellations officielles ──
  'Orion': ['Orion était un chasseur géant de la mythologie grecque, si fier qu’il prétendait pouvoir tuer tous les animaux de la Terre. Un scorpion le piqua, et les dieux les placèrent aux deux bouts du ciel : quand le Scorpion se lève, Orion se couche.',
    'Orion was a giant hunter in Greek myth, so proud he boasted he could kill every animal on Earth. A scorpion stung him, and the gods set them at opposite ends of the sky: when Scorpius rises, Orion sets.'],
  'Centaure': ['Le Centaure serait Chiron, le plus sage des centaures, qui fut le maître d’Achille et d’Asclépios. Blessé par erreur d’une flèche empoisonnée, il renonça à son immortalité et Zeus le plaça parmi les étoiles.',
    'The Centaur is said to be Chiron, the wisest of the centaurs, teacher of Achilles and Asclepius. Wounded by mistake with a poisoned arrow, he gave up his immortality and Zeus placed him among the stars.'],
  'Petit Lion': ['Le Petit Lion est une constellation jeune, dessinée en 1687 par l’astronome Johannes Hevelius entre le Lion et la Grande Ourse. Il n’a pas de légende ancienne : c’est un petit lionceau qui comble un coin de ciel vide.',
    'Leo Minor is a young constellation, drawn in 1687 by the astronomer Johannes Hevelius between Leo and the Great Bear. It has no ancient legend: it is a little lion cub filling an empty corner of the sky.'],
  'Bouvier': ['Le Bouvier mène les bœufs de la Grande Ourse autour du pôle, comme s’il les poussait sans fin dans les champs du ciel. Pour certains Grecs, c’était Arcas, le fils de Callisto, placé près de sa mère changée en ourse.',
    'The Herdsman drives the oxen of the Great Bear around the pole, as if pushing them forever through the fields of the sky. For some Greeks he was Arcas, son of Callisto, set beside his mother who had been turned into a bear.'],
  'Licorne': ['La Licorne a été ajoutée au ciel vers 1612 par le cartographe Petrus Plancius, dans un coin discret près d’Orion. Elle reprend l’animal des récits médiévaux, symbole de pureté que personne ne pouvait capturer.',
    'The Unicorn was added to the sky around 1612 by the mapmaker Petrus Plancius, in a quiet corner near Orion. It borrows the creature of medieval tales, a symbol of purity that no one could capture.'],
  'Eridan': ['Éridan est un fleuve céleste qui serpente depuis le pied d’Orion jusqu’au ciel du Sud. C’est là que tomba Phaéton, fils du Soleil, après avoir perdu le contrôle du char de son père.',
    'Eridanus is a celestial river winding from Orion’s foot down to the southern sky. It is where Phaethon, son of the Sun, fell after losing control of his father’s chariot.'],
  'Pégase': ['Pégase est le cheval ailé né du sang de Méduse quand Persée lui trancha la tête. Il aida le héros Bellérophon à vaincre la Chimère, puis s’envola jusqu’à l’Olympe.',
    'Pegasus is the winged horse born from Medusa’s blood when Perseus cut off her head. He helped the hero Bellerophon defeat the Chimera, then flew up to Olympus.'],
  'Carène': ['La Carène est la coque du navire Argo, sur lequel Jason et les Argonautes partirent chercher la Toison d’or. Ce grand bateau du ciel était si vaste qu’on l’a découpé en trois constellations : la Carène, la Poupe et les Voiles.',
    'Carina is the hull of the ship Argo, on which Jason and the Argonauts sailed for the Golden Fleece. This great sky ship was so large it was split into three constellations: the Keel, the Stern and the Sails.'],
  'Toucan': ['Le Toucan a été dessiné à la fin du 16e siècle d’après les récits des navigateurs hollandais qui exploraient les mers du Sud. Ils y voyaient des oiseaux qu’aucun Européen n’avait jamais vus, et les ont mis dans le ciel.',
    'The Toucan was drawn at the end of the 16th century from the tales of Dutch navigators exploring the southern seas. They saw birds no European had ever seen, and put them in the sky.'],
  'Microscope': ['Le Microscope a été créé vers 1752 par l’abbé Nicolas-Louis de Lacaille, qui cartographiait le ciel austral depuis le cap de Bonne-Espérance. Il voulait honorer les instruments de la science plutôt que les dieux.',
    'The Microscope was created around 1752 by abbé Nicolas-Louis de Lacaille, who mapped the southern sky from the Cape of Good Hope. He wanted to honour the instruments of science rather than the gods.'],
  'Coupe': ['La Coupe est le gobelet d’Apollon. Il envoya le Corbeau lui chercher de l’eau, mais l’oiseau traîna en route et mentit ; Apollon mit au ciel la coupe, le corbeau et le serpent, la coupe à jamais hors de portée de l’oiseau assoiffé.',
    'The Cup is Apollo’s goblet. He sent the Crow to fetch water, but the bird dawdled and lied; Apollo set the cup, the crow and the serpent in the sky, the cup forever out of reach of the thirsty bird.'],
  'Aigle': ['L’Aigle portait la foudre de Zeus et l’accompagnait partout. C’est lui qui enleva le jeune Ganymède pour l’emmener servir les dieux sur l’Olympe.',
    'The Eagle carried Zeus’s thunderbolts and went everywhere with him. It was the eagle that carried off young Ganymede to serve the gods on Olympus.'],
  'Corbeau': ['Le Corbeau était autrefois blanc et servait Apollon. Pour avoir menti, il fut puni : ses plumes devinrent noires et il fut cloué au ciel, juste à côté de la Coupe qu’il ne peut jamais atteindre.',
    'The Crow was once white and served Apollo. For lying, it was punished: its feathers turned black and it was pinned to the sky, right next to the Cup it can never reach.'],
  'Andromède': ['Andromède était une princesse enchaînée à un rocher pour être offerte à un monstre marin, à cause de la vanité de sa mère Cassiopée. Persée la délivra au dernier moment et l’épousa.',
    'Andromeda was a princess chained to a rock as an offering to a sea monster, because of her mother Cassiopeia’s vanity. Perseus freed her at the last moment and married her.'],
  'Cocher': ['Le Cocher serait Érichthonios, un roi d’Athènes qui inventa le char à quatre chevaux. On le dessine portant une chèvre et ses deux chevreaux dans les bras ; la chèvre, c’est la brillante Capella.',
    'The Charioteer is said to be Erichthonius, a king of Athens who invented the four-horse chariot. He is drawn carrying a goat and her two kids in his arms; the goat is bright Capella.'],
  'Serpent (queue)': ['Le Serpent est tenu à deux mains par Ophiuchus, le guérisseur, et c’est la seule constellation coupée en deux. Ici, c’est sa queue, qui file vers la Voie lactée.',
    'The Serpent is held in both hands by Ophiuchus, the healer, and it is the only constellation cut in two. This is its tail, slipping towards the Milky Way.'],
  'Dragon': ['Le Dragon serait Ladon, le gardien des pommes d’or du jardin des Hespérides, vaincu par Hercule. Il s’enroule autour du pôle Nord, comme s’il veillait encore sur un trésor.',
    'The Dragon is said to be Ladon, guardian of the golden apples in the garden of the Hesperides, defeated by Hercules. It coils around the North Pole, as if still guarding a treasure.'],
  'Lyre': ['La Lyre est celle d’Orphée, dont la musique charmait les bêtes, les arbres et même les pierres. Après sa mort, les Muses demandèrent à Zeus de placer son instrument parmi les étoiles.',
    'The Lyre belonged to Orpheus, whose music charmed beasts, trees and even stones. After his death, the Muses asked Zeus to set his instrument among the stars.'],
  'Baleine': ['La Baleine est le monstre marin envoyé par Poséidon pour dévorer Andromède. Persée le changea en pierre en lui montrant la tête de Méduse.',
    'The Whale is the sea monster Poseidon sent to devour Andromeda. Perseus turned it to stone by showing it Medusa’s head.'],
  'Serpent (tête)': ['Le Serpent est tenu à deux mains par Ophiuchus, le guérisseur, et c’est la seule constellation coupée en deux. Ici, c’est sa tête, qui se dresse vers la Couronne Boréale.',
    'The Serpent is held in both hands by Ophiuchus, the healer, and it is the only constellation cut in two. This is its head, rising towards the Northern Crown.'],
  'Colombe': ['La Colombe a été dessinée en 1592 par Petrus Plancius. Elle représente la colombe que Noé lâcha après le déluge et qui revint avec un rameau d’olivier.',
    'The Dove was drawn in 1592 by Petrus Plancius. It is the dove Noah released after the flood, which came back with an olive branch.'],
  'Petite Ourse': ['Au bout de la queue de la Petite Ourse brille l’étoile Polaire, qui reste presque immobile au-dessus du pôle Nord. Les marins s’en servaient pour retrouver leur route la nuit.',
    'At the tip of the Little Bear’s tail shines Polaris, which stays almost still above the North Pole. Sailors used it to find their way at night.'],
  'Cygne': ['Le Cygne est Zeus lui-même, qui prit la forme d’un cygne pour approcher la reine Léda. Il vole le long de la Voie lactée, les ailes grandes ouvertes, en dessinant une croix.',
    'The Swan is Zeus himself, who took the form of a swan to approach Queen Leda. It flies along the Milky Way with wings spread wide, drawing a cross.'],
  'Poupe': ['La Poupe est l’arrière du navire Argo, celui de Jason et des Argonautes. Elle formait autrefois avec la Carène et les Voiles un seul immense bateau, le plus grand du ciel.',
    'Puppis is the stern of the ship Argo, the ship of Jason and the Argonauts. Together with the Keel and the Sails it once formed a single huge ship, the largest in the sky.'],
  'Paon': ['Le Paon a été dessiné par les navigateurs hollandais de la fin du 16e siècle. Dans la légende grecque, Héra plaça sur la queue du paon les cent yeux du géant Argus.',
    'The Peacock was drawn by Dutch navigators at the end of the 16th century. In Greek legend, Hera placed the hundred eyes of the giant Argus on the peacock’s tail.'],
  'Dauphin': ['Le Dauphin fut envoyé par Poséidon pour retrouver la néréide Amphitrite, qui se cachait au fond de la mer. Il la convainquit d’épouser le dieu, qui le remercia en le plaçant au ciel.',
    'The Dolphin was sent by Poseidon to find the sea nymph Amphitrite, who was hiding at the bottom of the sea. It persuaded her to marry the god, who thanked it with a place in the sky.'],
  'Céphée': ['Céphée était le roi d’Éthiopie, mari de Cassiopée et père d’Andromède. Il est assis au ciel près de sa famille, la tête tout près de l’étoile Polaire.',
    'Cepheus was the king of Ethiopia, husband of Cassiopeia and father of Andromeda. He sits in the sky beside his family, his head close to the Pole Star.'],
  'Horloge': ['L’Horloge a été créée par Lacaille vers 1752, en l’honneur de l’horloge à pendule qui permettait enfin de mesurer le temps avec précision. Elle balance doucement au-dessus de l’horizon sud.',
    'The Clock was created by Lacaille around 1752, honouring the pendulum clock that finally allowed time to be measured precisely. It swings gently above the southern horizon.'],
  'Mouche': ['La Mouche est la seule constellation qui représente un insecte. Les navigateurs hollandais l’ont placée au ciel du Sud à la fin du 16e siècle, tout près de la Croix du Sud.',
    'The Fly is the only constellation that shows an insect. Dutch navigators placed it in the southern sky at the end of the 16th century, right next to the Southern Cross.'],
  'Couronne Boréale': ['La Couronne Boréale est le diadème que Dionysos offrit à Ariane, abandonnée sur l’île de Naxos par Thésée. Pour elle, il lança la couronne dans le ciel, où ses joyaux devinrent des étoiles.',
    'The Northern Crown is the diadem Dionysus gave Ariadne, abandoned on the island of Naxos by Theseus. For her he threw the crown into the sky, where its jewels became stars.'],
  'Phénix': ['Le Phénix est l’oiseau qui renaît de ses cendres : quand il sent la fin venir, il se brûle dans son nid, et un jeune phénix s’envole des flammes. Les navigateurs hollandais l’ont placé au ciel du Sud.',
    'The Phoenix is the bird reborn from its ashes: when it feels its end coming, it burns in its nest, and a young phoenix flies out of the flames. Dutch navigators placed it in the southern sky.'],
  'Dorade': ['La Dorade est un poisson des mers chaudes, vu par les navigateurs hollandais qui l’ont mise au ciel. Elle abrite le Grand Nuage de Magellan, une petite galaxie voisine de la nôtre.',
    'The Goldfish, or dorado, is a fish of warm seas, seen by the Dutch navigators who put it in the sky. It holds the Large Magellanic Cloud, a small galaxy next to ours.'],
  'Lièvre': ['Le Lièvre se cache aux pieds d’Orion, le chasseur, poursuivi par ses chiens. Une légende dit que l’île de Léros fut envahie de lièvres, et qu’on les mit au ciel pour se souvenir de ce fléau.',
    'The Hare hides at the feet of Orion the hunter, chased by his dogs. A legend says the island of Leros was overrun with hares, and they were put in the sky to remember the plague.'],
  'Hydre Femelle': ['L’Hydre est la plus grande constellation du ciel. Elle serait le serpent qu’Apollon plaça près de la Coupe et du Corbeau, ou l’hydre de Lerne aux têtes qui repoussaient, vaincue par Hercule.',
    'Hydra is the largest constellation in the sky. It is said to be the serpent Apollo set beside the Cup and the Crow, or the Lernaean Hydra whose heads grew back, defeated by Hercules.'],
  'Poisson Volant': ['Le Poisson Volant rappelle ces poissons qui bondissent hors de l’eau et planent au-dessus des vagues des mers tropicales. Les navigateurs hollandais, émerveillés, l’ont mis au ciel du Sud.',
    'The Flying Fish recalls the fish that leap out of the water and glide above the waves of tropical seas. The Dutch navigators, amazed, put it in the southern sky.'],
  'Ophiuchus': ['Ophiuchus est Asclépios, le dieu de la médecine, qui savait même ramener les morts à la vie. Il tient un serpent, symbole de guérison qu’on retrouve encore sur les pharmacies.',
    'Ophiuchus is Asclepius, god of medicine, who could even bring the dead back to life. He holds a serpent, a symbol of healing still seen on pharmacies today.'],
  'Loup': ['Le Loup est tenu à bout de lance par le Centaure. Pour les Grecs, c’était juste une bête sauvage ; on raconte aussi que c’est Lycaon, un roi changé en loup par Zeus pour sa cruauté.',
    'The Wolf is held at the end of the Centaur’s spear. For the Greeks it was simply a wild beast; it is also said to be Lycaon, a king turned into a wolf by Zeus for his cruelty.'],
  'Capricorne': ['Le Capricorne est une chèvre à queue de poisson. On raconte que le dieu Pan sauta dans une rivière pour fuir le monstre Typhon : la moitié de son corps sous l’eau devint poisson.',
    'Capricorn is a goat with a fish’s tail. It is said the god Pan jumped into a river to escape the monster Typhon: the half of his body under the water became a fish.'],
  'Grande Ourse': ['La Grande Ourse est Callisto, une nymphe changée en ourse par la jalousie d’Héra. Zeus la plaça au ciel, où elle tourne sans jamais se coucher sous l’horizon.',
    'The Great Bear is Callisto, a nymph turned into a bear by Hera’s jealousy. Zeus placed her in the sky, where she circles without ever setting below the horizon.'],
  'Vierge': ['La Vierge serait Déméter, déesse des moissons, ou Astrée, la déesse de la justice, dernière immortelle à avoir quitté la Terre. Elle tient un épi de blé : l’étoile Spica.',
    'Virgo is said to be Demeter, goddess of the harvest, or Astraea, goddess of justice, the last immortal to leave the Earth. She holds an ear of wheat: the star Spica.'],
  'Girafe': ['La Girafe a été ajoutée au ciel en 1612 par Petrus Plancius, dans une région vide près du pôle Nord. Ses étoiles sont si pâles qu’il faut un ciel très noir pour la voir.',
    'The Giraffe was added to the sky in 1612 by Petrus Plancius, in an empty region near the North Pole. Its stars are so faint that you need a very dark sky to see it.'],
  'Persée': ['Persée est le héros qui trancha la tête de Méduse, dont le regard changeait en pierre. Il tient encore la tête au ciel : son œil qui clignote, c’est l’étoile Algol.',
    'Perseus is the hero who cut off the head of Medusa, whose gaze turned people to stone. He still holds the head in the sky: its winking eye is the star Algol.'],
  'Autel': ['L’Autel est celui où les dieux jurèrent fidélité avant leur combat contre les Titans. La fumée qui monte de l’autel, c’est la Voie lactée.',
    'The Altar is where the gods swore loyalty before their war against the Titans. The smoke rising from the altar is the Milky Way.'],
  'Grand Chien': ['Le Grand Chien suit Orion, son maître chasseur. Sur sa gueule brille Sirius, l’étoile la plus brillante de tout le ciel de nuit.',
    'The Great Dog follows Orion, its hunter master. On its muzzle shines Sirius, the brightest star in the whole night sky.'],
  'Caméléon': ['Le Caméléon a été dessiné par les navigateurs hollandais, près du pôle Sud. Il guette la Mouche voisine, comme s’il allait l’attraper d’un coup de langue.',
    'The Chameleon was drawn by Dutch navigators near the South Pole. It watches the neighbouring Fly, as if about to catch it with its tongue.'],
  'Poisson Austral': ['Le Poisson Austral boit l’eau que lui verse le Verseau. Pour les Grecs, c’est lui qui aurait sauvé la déesse Isis tombée dans un lac ; son œil brillant est l’étoile Fomalhaut.',
    'The Southern Fish drinks the water poured by Aquarius. For the Greeks it saved the goddess Isis when she fell into a lake; its bright eye is the star Fomalhaut.'],
  'Verseau': ['Le Verseau est Ganymède, le jeune berger que Zeus fit monter sur l’Olympe pour servir à boire aux dieux. Il verse de sa jarre un fleuve d’eau qui coule vers le Poisson Austral.',
    'Aquarius is Ganymede, the young shepherd Zeus brought up to Olympus to pour drinks for the gods. From his jar he pours a stream of water flowing to the Southern Fish.'],
  'Scorpion': ['Le Scorpion fut envoyé par la déesse Gaïa pour punir Orion, qui se vantait de pouvoir tuer tous les animaux. Il le piqua au talon, et depuis, les deux ne sont jamais dans le ciel en même temps.',
    'The Scorpion was sent by the goddess Gaia to punish Orion, who boasted he could kill every animal. It stung his heel, and since then the two are never in the sky at the same time.'],
  'Voiles': ['Les Voiles sont celles du navire Argo, qui portait Jason vers la Toison d’or. Avec la Carène et la Poupe, elles formaient le plus grand bateau du ciel.',
    'The Sails belong to the ship Argo, which carried Jason towards the Golden Fleece. With the Keel and the Stern, they made up the largest ship in the sky.'],
  'Hydre Mâle': ['L’Hydre Mâle est un petit serpent d’eau, ajouté par les navigateurs hollandais pour faire pendant à la grande Hydre. Il se glisse entre les deux Nuages de Magellan, près du pôle Sud.',
    'Hydrus is a small water snake, added by Dutch navigators as a partner to the great Hydra. It slips between the two Magellanic Clouds, near the South Pole.'],
  'Balance': ['La Balance est la seule constellation du zodiaque qui représente un objet. Elle est tenue par Astrée, la déesse de la justice, qui pèse les âmes et les actes.',
    'Libra is the only zodiac constellation that shows an object. It is held by Astraea, goddess of justice, who weighs souls and deeds.'],
  'Grue': ['La Grue a été dessinée par les navigateurs hollandais à la fin du 16e siècle. Elle étire son long cou dans le ciel du Sud, comme un oiseau en plein vol.',
    'The Crane was drawn by Dutch navigators at the end of the 16th century. It stretches its long neck across the southern sky like a bird in flight.'],
  'Couronne Australe': ['La Couronne Australe est une couronne de laurier posée aux pieds du Sagittaire. Certains disent que Dionysos la plaça au ciel après être allé chercher sa mère aux Enfers.',
    'The Southern Crown is a laurel wreath lying at the feet of Sagittarius. Some say Dionysus placed it in the sky after bringing his mother back from the Underworld.'],
  'Lion': ['Le Lion est le lion de Némée, dont la peau ne pouvait être percée par aucune arme. Hercule l’étouffa à mains nues, puis porta sa peau comme une armure.',
    'Leo is the Nemean lion, whose skin no weapon could pierce. Hercules strangled it with his bare hands, then wore its skin as armour.'],
  'Gémeaux': ['Les Gémeaux sont Castor et Pollux, deux frères inséparables. Quand Castor mourut, Pollux, immortel, demanda à partager sa vie avec lui ; Zeus les réunit au ciel, côte à côte.',
    'Gemini are Castor and Pollux, two inseparable brothers. When Castor died, the immortal Pollux asked to share his life with him; Zeus reunited them in the sky, side by side.'],
  'Indien': ['L’Indien a été dessiné par les navigateurs hollandais de la fin du 16e siècle. Il représente un habitant des terres lointaines qu’ils découvraient, tenant des flèches.',
    'The Indian was drawn by Dutch navigators at the end of the 16th century. It shows a person from the faraway lands they were discovering, holding arrows.'],
  'Lynx': ['Le Lynx a été créé en 1687 par Johannes Hevelius. Ses étoiles sont si faibles, disait-il, qu’il faut des yeux de lynx pour les voir.',
    'The Lynx was created in 1687 by Johannes Hevelius. Its stars are so faint, he said, that you need the eyes of a lynx to see them.'],
  'Petit Renard': ['Le Petit Renard a été dessiné par Johannes Hevelius en 1687, tenant une oie dans sa gueule. Il se faufile dans la Voie lactée, entre le Cygne et l’Aigle.',
    'The Little Fox was drawn by Johannes Hevelius in 1687, holding a goose in its jaws. It slips through the Milky Way, between the Swan and the Eagle.'],
  'Poissons': ['Les Poissons sont Aphrodite et son fils Éros, qui se changèrent en poissons pour fuir le monstre Typhon. Ils s’attachèrent par une corde pour ne jamais se perdre.',
    'Pisces are Aphrodite and her son Eros, who turned into fish to escape the monster Typhon. They tied themselves together with a cord so they would never be separated.'],
  'Sagittaire': ['Le Sagittaire est un centaure archer, qui vise le cœur du Scorpion de sa flèche. En regardant vers lui, on regarde vers le centre de notre galaxie.',
    'Sagittarius is a centaur archer, aiming his arrow at the heart of the Scorpion. Looking towards him, you look towards the centre of our galaxy.'],
  'Lézard': ['Le Lézard a été créé par Johannes Hevelius en 1687, glissé entre le Cygne et Andromède. C’est un petit zigzag d’étoiles, comme un lézard qui se faufile entre deux pierres.',
    'The Lizard was created by Johannes Hevelius in 1687, slipped between the Swan and Andromeda. It is a small zigzag of stars, like a lizard darting between two stones.'],
  'Hercule': ['Hercule est le héros aux douze travaux, fils de Zeus, d’une force immense. Il est dessiné à genoux, un pied posé sur la tête du Dragon.',
    'Hercules is the hero of the twelve labours, son of Zeus, of immense strength. He is drawn kneeling, one foot on the Dragon’s head.'],
  'Cancer': ['Le Cancer est le crabe qu’Héra envoya pour gêner Hercule pendant son combat contre l’Hydre. Hercule l’écrasa du pied, et Héra le récompensa d’une place au ciel.',
    'Cancer is the crab Hera sent to trouble Hercules during his fight with the Hydra. Hercules crushed it underfoot, and Hera rewarded it with a place in the sky.'],
  'Taureau': ['Le Taureau est Zeus, changé en taureau blanc pour enlever la princesse Europe et l’emporter sur son dos à travers la mer. Sur son épaule brillent les Pléiades, sept sœurs devenues étoiles.',
    'Taurus is Zeus, turned into a white bull to carry off Princess Europa on his back across the sea. On his shoulder shine the Pleiades, seven sisters who became stars.'],
  'Cassiopée': ['Cassiopée était une reine si fière de sa beauté qu’elle se disait plus belle que les nymphes de la mer. Pour la punir, Poséidon l’attacha au ciel sur son trône, la tête en bas une partie de l’année.',
    'Cassiopeia was a queen so proud of her beauty that she claimed to be lovelier than the sea nymphs. To punish her, Poseidon bound her to the sky on her throne, upside down for part of the year.'],
  // anciennes figures (semaines d'avant octobre 2026)
  'Croix du Sud': ['La Croix du Sud est la plus petite constellation du ciel, mais l’une des plus connues. Les marins de l’hémisphère Sud s’en servaient pour trouver le pôle Sud.',
    'The Southern Cross is the smallest constellation in the sky, but one of the best known. Sailors in the southern hemisphere used it to find the South Pole.'],
  'Pléiades': ['Les Pléiades sont sept sœurs, filles du géant Atlas, poursuivies par Orion. Zeus les changea en colombes, puis en étoiles, sur l’épaule du Taureau.',
    'The Pleiades are seven sisters, daughters of the giant Atlas, chased by Orion. Zeus turned them into doves, then into stars, on the shoulder of the Bull.'],

  // ── constellations chinoises anciennes : ce qu'elles représentaient ──
  'La Colline verte': ['Dans le ciel chinois, la Colline verte représentait un pays lointain du Sud, au-delà des frontières de l’Empire. Ses sept étoiles marquaient les peuples barbares qu’on surveillait depuis la cour.',
    'In the Chinese sky, Green Hill stood for a faraway land in the south, beyond the Empire’s borders. Its seven stars marked the foreign peoples watched from the court.'],
  'Le Mur gauche de la Cité pourpre': ['La Cité pourpre était le palais céleste de l’Empereur, autour de l’étoile Polaire. Ce mur gauche, fait de ministres et de généraux, protégeait le souverain du ciel.',
    'The Purple Forbidden Enclosure was the Emperor’s heavenly palace, around the Pole Star. This left wall, made of ministers and generals, protected the ruler of the sky.'],
  'Xuanyuan, l’Empereur jaune': ['Xuanyuan est le nom de l’Empereur jaune, ancêtre légendaire des Chinois. Ses étoiles dessinaient aussi un dragon jaune qui commandait la pluie et le tonnerre.',
    'Xuanyuan is the name of the Yellow Emperor, legendary ancestor of the Chinese people. Its stars also drew a yellow dragon commanding rain and thunder.'],
  'La Ligne des remparts': ['La Ligne des remparts était une longue fortification qui protégeait le camp de l’armée du Nord. Ses étoiles alignées formaient un mur de soldats prêts à repousser les envahisseurs.',
    'The Line of Ramparts was a long fortification guarding the camp of the Northern Army. Its row of stars made a wall of soldiers ready to push back invaders.'],
  'La Clôture extérieure': ['La Clôture extérieure était une haie qui protégeait les toilettes du ciel. Les astronomes chinois avaient tout prévu dans leur ville céleste, même les recoins les plus modestes.',
    'The Outer Fence was a screen hiding the sky’s privy. Chinese astronomers planned everything in their heavenly city, even its humblest corners.'],
  'La Tortue de rivière': ['La Tortue de rivière vivait près de la Voie lactée, que les Chinois appelaient le Fleuve d’argent. Quand elle brillait fort, on disait que les eaux allaient monter.',
    'The River Turtle lived near the Milky Way, which the Chinese called the Silver River. When it shone brightly, people said the waters would rise.'],
  'Les Sept Excellences': ['Les Sept Excellences étaient les sept plus hauts ministres de la cour céleste. Ils conseillaient l’Empereur du ciel et veillaient à la justice du royaume.',
    'The Seven Excellencies were the seven highest ministers of the heavenly court. They advised the Emperor of the sky and watched over justice in the realm.'],
  'Le Mausolée': ['Le Mausolée était le grand tombeau des souverains du ciel. Ses étoiles gardaient la mémoire des ancêtres, qu’on honorait avec respect.',
    'The Mausoleum was the great tomb of the rulers of the sky. Its stars kept the memory of the ancestors, honoured with respect.'],
  'La Grue': ['Pour les Chinois, la grue est l’oiseau de la longévité, qui porte les sages vers les immortels. Elle volait au ciel du Sud, porteuse de longue vie.',
    'For the Chinese, the crane is the bird of long life, carrying sages to the immortals. It flew in the southern sky, a bearer of longevity.'],
  'Le Panier à feuilles de mûrier': ['Le Panier à feuilles de mûrier servait à nourrir les vers à soie de l’Impératrice. La soie était si précieuse qu’elle avait sa place dans les étoiles.',
    'The Basket for Mulberry Leaves fed the Empress’s silkworms. Silk was so precious that it had its own place among the stars.'],
  'La Règle céleste': ['La Règle céleste représentait les lois et la discipline du ciel. Ses étoiles rappelaient que même le monde des étoiles avait ses règles.',
    'The Celestial Discipline stood for the laws and order of the sky. Its stars reminded people that even the world of stars had its rules.'],
  'Le Palais du repos': ['Le Palais du repos était une résidence où l’Empereur venait se reposer, près du grand campement céleste. Un lieu calme au milieu des armées du ciel.',
    'The Resting Palace was a residence where the Emperor came to rest, near the great heavenly camp. A calm place among the armies of the sky.'],
  'Les Ailes': ['Les Ailes étaient l’une des vingt-huit demeures de la Lune, les étapes de son voyage au fil du mois. Elles formaient les ailes de l’Oiseau vermillon, gardien du Sud.',
    'The Wings were one of the twenty-eight lunar mansions, the stages of the Moon’s journey through the month. They formed the wings of the Vermilion Bird, guardian of the south.'],
  'Les Douze États': ['Les Douze États représentaient les anciens royaumes de la Chine d’avant l’Empire. Chaque étoile portait le nom d’un pays, comme une carte du monde au ciel.',
    'The Twelve States stood for the old kingdoms of China before the Empire. Each star bore the name of a land, like a map of the world in the sky.'],
  'Les Piliers du Filet': ['Les Piliers étaient des poteaux plantés près de la demeure du Filet. On y attachait les filets de chasse, pour attraper le gibier du ciel.',
    'The Pillars were posts set near the Net mansion. Hunting nets were tied to them, to catch the game of the sky.'],
  'L’Officier du marché': ['L’Officier du marché veillait à l’ordre et aux prix dans les marchés du ciel. Grâce à lui, les échanges restaient honnêtes.',
    'The Market Officer kept order and fair prices in the markets of the sky. Thanks to him, trade stayed honest.'],
  'Les Remparts célestes': ['Les Remparts célestes entouraient une prison du ciel. Leurs étoiles formaient un mur que personne ne pouvait franchir.',
    'The Celestial Ramparts surrounded a prison of the sky. Their stars made a wall no one could cross.'],
  'La Queue': ['La Queue était l’une des vingt-huit demeures de la Lune. C’était la queue du Dragon azur, gardien de l’Est, qui se recourbe comme celle de notre Scorpion.',
    'The Tail was one of the twenty-eight lunar mansions. It was the tail of the Azure Dragon, guardian of the east, curling like that of our Scorpion.'],
  'Le Grand Général du Ciel': ['Le Grand Général du Ciel commandait les armées célestes. Quand ses étoiles brillaient fort, on pensait que l’Empire serait en sécurité.',
    'The Great General of Heaven commanded the heavenly armies. When its stars shone brightly, people believed the Empire would be safe.'],
  'Les Trois Étoiles': ['Les Trois Étoiles étaient l’une des vingt-huit demeures de la Lune, autour des trois étoiles de la ceinture d’Orion. Elles représentaient un guerrier du Tigre blanc, gardien de l’Ouest.',
    'The Three Stars were one of the twenty-eight lunar mansions, around the three stars of Orion’s belt. They stood for a warrior of the White Tiger, guardian of the west.'],
  'La Corde enroulée': ['La Corde enroulée était une prison pour les gens du peuple, dessinée par l’anneau de la Couronne Boréale. Quand peu d’étoiles s’y voyaient, on disait qu’il y avait peu de prisonniers.',
    'The Coiled Thong was a prison for common folk, drawn by the ring of the Northern Crown. When few stars were visible inside, people said there were few prisoners.'],
  'Les Jambes': ['Les Jambes étaient la première demeure de la Lune dans le quartier du Tigre blanc. Ses étoiles faisaient aussi penser à l’enjambée d’un géant.',
    'The Legs were the first lunar mansion in the White Tiger’s quarter. Its stars also suggested the stride of a giant.'],
  'Le Mur gauche du Marché céleste': ['Le Marché céleste était une grande place de commerce entourée de murs. Ce mur gauche portait les noms des royaumes qui venaient y échanger leurs marchandises.',
    'The Heavenly Market was a great trading square surrounded by walls. This left wall bore the names of the kingdoms that came to trade their goods.'],
  'Les Gardes impériaux': ['Les Gardes impériaux veillaient sur les cavaliers de l’Empereur. Ils montaient la garde à cheval, prêts à partir au galop.',
    'The Imperial Guards watched over the Emperor’s horsemen. They stood guard on horseback, ready to gallop away.'],
  'La Grande Cour des chars': ['La Grande Cour des chars était l’endroit où l’on rangeait les chars de l’Empereur. Ses étoiles alignées faisaient penser à une écurie céleste.',
    'The Big Yard for Chariots was where the Emperor’s chariots were kept. Its row of stars recalled a heavenly stable.'],
  'L’Oiseau exotique': ['L’Oiseau exotique a été ajouté au ciel chinois au 17e siècle, d’après les cartes européennes du ciel austral. C’est l’oiseau de paradis, venu des mers du Sud.',
    'The Exotic Bird was added to the Chinese sky in the 17th century, from European maps of the southern sky. It is the bird of paradise, from the southern seas.'],
  'Les Piliers de la Corne': ['Les Piliers de la Corne soutenaient la demeure de la Corne, la tête du Dragon azur. Ils annonçaient le printemps, quand le Dragon se levait le soir.',
    'The Pillars of the Horn held up the Horn mansion, the head of the Azure Dragon. They announced spring, when the Dragon rose in the evening.'],
  'Le Serpent volant': ['Le Serpent volant était un serpent ailé qui glissait au ciel du Nord, au bord de la Voie lactée. Dans les légendes, il chevauchait les nuages et la brume.',
    'The Flying Serpent was a winged snake gliding through the northern sky, at the edge of the Milky Way. In legends it rode the clouds and mist.'],
  'La Petite Louche': ['La Petite Louche a été ajoutée au ciel chinois au 17e siècle, d’après les cartes européennes. Elle rappelait la Grande Louche, que nous appelons la Grande Ourse.',
    'The Little Dipper was added to the Chinese sky in the 17th century, from European maps. It echoed the Great Dipper, which we call the Great Bear.'],
  'Les Huit Récoltes': ['Les Huit Récoltes représentaient les huit grandes cultures qui nourrissaient l’Empire, comme le riz, le blé ou le millet. Quand elles brillaient, on espérait de bonnes moissons.',
    'The Eight Kinds of Crops stood for the eight great harvests that fed the Empire, like rice, wheat and millet. When they shone, people hoped for good crops.'],
  'Le Sceau céleste': ['Le Sceau céleste était le jeton officiel que portaient les envoyés de l’Empereur. Il prouvait qu’ils parlaient en son nom.',
    'The Celestial Tally was the official token carried by the Emperor’s envoys. It proved they spoke in his name.'],
  'La Tête chevelue': ['La Tête chevelue était l’une des vingt-huit demeures de la Lune, autour des Pléiades. Les Chinois y voyaient la chevelure flottante d’un guerrier.',
    'The Hairy Head was one of the twenty-eight lunar mansions, around the Pleiades. The Chinese saw in it the flowing hair of a warrior.'],
  'Le Filet': ['Le Filet était une demeure de la Lune, en forme de filet de chasse pour attraper les lapins. On disait que lorsque la Lune y passait, la pluie arrivait.',
    'The Net was a lunar mansion shaped like a hunting net for catching rabbits. It was said that when the Moon passed through it, rain would come.'],
  'Le Gué céleste': ['Le Gué céleste était un passage pour traverser le Fleuve d’argent, la Voie lactée. C’est là, dit-on, que la tisserande et le bouvier se retrouvent une fois par an.',
    'The Celestial Ford was a crossing over the Silver River, the Milky Way. It is said to be where the weaver girl and the cowherd meet once a year.'],
  'L’Étoile': ['L’Étoile était une demeure de la Lune, au cœur de l’Oiseau vermillon, gardien du Sud. Son étoile principale, rouge, était vue comme le cœur de l’oiseau.',
    'The Star was a lunar mansion at the heart of the Vermilion Bird, guardian of the south. Its main red star was seen as the bird’s heart.'],
  'L’Arc et la Flèche': ['L’Arc et la Flèche étaient pointés sur le Loup céleste, Sirius, pour l’empêcher de faire des ravages. L’archer veillait sur le ciel du Sud.',
    'The Bow and Arrow were aimed at the Celestial Wolf, Sirius, to stop it from causing havoc. The archer kept watch over the southern sky.'],
  'Le Mur droit de la Cité pourpre': ['La Cité pourpre était le palais céleste de l’Empereur, autour de l’étoile Polaire. Ce mur droit, fait de ministres et de gardes, refermait l’enceinte.',
    'The Purple Forbidden Enclosure was the Emperor’s heavenly palace, around the Pole Star. This right wall, made of ministers and guards, closed the enclosure.'],
  'Les Prés célestes': ['Les Prés célestes étaient de grands pâturages où paissaient les troupeaux de l’Empereur. Un coin de campagne au milieu du ciel.',
    'The Celestial Meadows were wide pastures where the Emperor’s herds grazed. A patch of countryside in the middle of the sky.'],
  'Le Pilier du dais': ['Le Pilier du dais tenait le grand parasol qui protégeait l’Empereur. Sans lui, le dais céleste se serait effondré.',
    'The Canopy Support held up the great parasol that sheltered the Emperor. Without it, the heavenly canopy would have collapsed.'],
  'L’Arsenal': ['L’Arsenal était le grand entrepôt d’armes et de chars de l’armée céleste. Quand il brillait, on pensait que l’armée était forte.',
    'The Arsenal was the great storehouse of weapons and chariots of the heavenly army. When it shone, the army was thought to be strong.'],
  'La Bannière aux trois étoiles': ['La Bannière aux trois étoiles était un étendard de guerre, planté près des Trois Étoiles d’Orion. Il signalait l’armée en marche.',
    'The Banner of Three Stars was a war standard, planted near Orion’s Three Stars. It signalled the army on the march.'],
  'Le Saule': ['Le Saule était une demeure de la Lune, le bec de l’Oiseau vermillon, gardien du Sud. Ses étoiles courbées rappelaient les branches d’un saule.',
    'The Willow was a lunar mansion, the beak of the Vermilion Bird, guardian of the south. Its curved stars recalled the branches of a willow.'],
  'Le Paon': ['Le Paon a été ajouté au ciel chinois au 17e siècle, d’après les cartes européennes du ciel austral. Pour les Chinois, le paon était un oiseau de noblesse et de beauté.',
    'The Peafowl was added to the Chinese sky in the 17th century, from European maps of the southern sky. For the Chinese, the peacock was a bird of nobility and beauty.'],
  'Le Drapeau de gauche': ['Le Drapeau de gauche flottait à côté de l’Aigle, près du Bouvier céleste. Il marquait le flanc gauche de l’armée du ciel.',
    'The Left Flag flew beside the Eagle, near the heavenly Cowherd. It marked the left flank of the sky’s army.'],
  'Le Char': ['Le Char était la dernière demeure de la Lune, la queue de l’Oiseau vermillon. Ses quatre étoiles dessinaient un char qui portait les vents.',
    'The Chariot was the last lunar mansion, the tail of the Vermilion Bird. Its four stars drew a chariot that carried the winds.'],
  'Le Grenier rond du Ciel': ['Le Grenier rond du Ciel gardait les réserves de grain de l’Empire. Quand il brillait, on pensait que personne n’aurait faim.',
    'The Circular Celestial Granary kept the Empire’s grain stores. When it shone, it was thought no one would go hungry.'],
  'La Perse': ['La Perse a été ajoutée au ciel chinois au 17e siècle, d’après les cartes européennes. Elle reprend le héros Persée, dont le nom évoquait aux Chinois le lointain pays de Perse.',
    'Persia was added to the Chinese sky in the 17th century, from European maps. It took over the hero Perseus, whose name reminded the Chinese of the faraway land of Persia.'],
  'Les Officiers de la Garde': ['Les Officiers de la Garde protégeaient le palais de l’Empereur, de jour comme de nuit. Leurs étoiles serrées formaient une petite troupe fidèle.',
    'The Officers of the Imperial Guard protected the Emperor’s palace day and night. Their close stars formed a small, loyal troop.'],
  'Le Chien céleste': ['Le Chien céleste gardait les portes du ciel du Sud. Dans les légendes, il pouvait aussi croquer le Soleil ou la Lune lors des éclipses.',
    'The Celestial Dog guarded the gates of the southern sky. In legends it could also bite the Sun or the Moon during eclipses.'],
  'Le Crochet céleste': ['Le Crochet céleste était un grand crochet suspendu au ciel du Nord, près de Céphée. On l’imaginait retenant le ciel, comme un crochet qui tient une tenture.',
    'The Celestial Hook was a great hook hanging in the northern sky, near Cepheus. It was imagined holding up the sky, like a hook holding a curtain.'],
  'L’Oiseau de feu': ['L’Oiseau de feu a été ajouté au ciel chinois au 17e siècle, d’après les cartes européennes. C’est notre Phénix, l’oiseau qui renaît de ses flammes.',
    'The Firebird was added to the Chinese sky in the 17th century, from European maps. It is our Phoenix, the bird reborn from its flames.'],
  'Le Mur droit du Marché céleste': ['Le Marché céleste était une grande place de commerce entourée de murs. Ce mur droit portait les noms des royaumes de l’Ouest venus y vendre leurs trésors.',
    'The Heavenly Market was a great trading square surrounded by walls. This right wall bore the names of the western kingdoms that came to sell their treasures.'],
  'Les Drapeaux du trône': ['Les Drapeaux du trône flottaient autour de la place où siégeait l’Empereur. Ils annonçaient qu’il était présent.',
    'The Seat Flags flew around the place where the Emperor sat. They announced his presence.'],
  'Le Drapeau impérial': ['Le Drapeau impérial, aux neuf rubans, était l’étendard militaire de l’Empereur. On le levait pour rassembler les troupes.',
    'The Imperial Military Flag, with its nine ribbons, was the Emperor’s war banner. It was raised to gather the troops.'],
  'La Maison des hôtes': ['La Maison des hôtes accueillait les voyageurs et les envoyés venus de loin. Une auberge céleste, toujours ouverte.',
    'The Guest House welcomed travellers and envoys from far away. A heavenly inn, always open.'],
  'La Garde royale': ['La Garde royale entourait l’Empereur pendant ses audiences. Ses soldats veillaient à ce que rien ne trouble la cour.',
    'The Royal Guards surrounded the Emperor during his audiences. Its soldiers made sure nothing disturbed the court.'],
  'La Serrure céleste': ['La Serrure céleste fermait une porte du ciel, près de l’écliptique. Elle s’ouvrait pour laisser passer le Soleil et la Lune.',
    'The Celestial Keyhole locked a gate of the sky, near the ecliptic. It opened to let the Sun and the Moon pass.'],
  'Le Puits': ['Le Puits était une demeure de la Lune, première du quartier de l’Oiseau vermillon. Ses étoiles dessinaient la margelle d’un puits où l’on puisait l’eau.',
    'The Well was a lunar mansion, the first in the Vermilion Bird’s quarter. Its stars drew the rim of a well where water was drawn.'],
  'Le Drapeau de droite': ['Le Drapeau de droite flottait de l’autre côté de l’Aigle, près du Bouvier céleste. Il marquait le flanc droit de l’armée du ciel.',
    'The Right Flag flew on the other side of the Eagle, near the heavenly Cowherd. It marked the right flank of the sky’s army.'],
  'La Barque céleste': ['La Barque céleste naviguait sur le Fleuve d’argent, la Voie lactée. Elle aidait à traverser les eaux du ciel quand elles montaient.',
    'The Celestial Boat sailed on the Silver River, the Milky Way. It helped cross the sky’s waters when they rose.'],
  'Le Bec de l’oiseau': ['Le Bec de l’oiseau a été ajouté au ciel chinois au 17e siècle, d’après les cartes européennes. C’est notre Toucan, avec son grand bec.',
    'The Bird’s Beak was added to the Chinese sky in the 17th century, from European maps. It is our Toucan, with its big beak.'],
  'Le Dais de l’Empereur': ['Le Dais de l’Empereur était le grand parasol orné qui l’abritait, dessiné par les étoiles de Cassiopée. Il couvrait le souverain du ciel.',
    'The Canopy of the Emperor was the great ornate parasol that sheltered him, drawn by the stars of Cassiopeia. It covered the ruler of the sky.'],
  'Le Verger céleste': ['Le Verger céleste était un jardin d’arbres fruitiers qui nourrissait la cour. Ses étoiles dessinaient des rangées d’arbres le long d’Éridan.',
    'The Celestial Orchard was a garden of fruit trees that fed the court. Its stars drew rows of trees along Eridanus.'],
};

export function legende(nom) { const l = L[nom]; return l ? (EN ? l[1] : l[0]) : ''; }
